/*
 * Cashfree Payment Gateway APIs
 *
 * Cashfree's Payment Gateway APIs provide developers with a streamlined pathway to integrate advanced payment processing capabilities into their applications, platforms and websites.
 *
 * The version of the OpenAPI document: 2026-01-01
 * Contact: developers@cashfree.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using cashfree-dotnet-pg-sdk.Model;
using cashfree-dotnet-pg-sdk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace cashfree-dotnet-pg-sdk.Test.Model
{
    /// <summary>
    ///  Class for testing BalanceDetails
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class BalanceDetailsTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for BalanceDetails
        //private BalanceDetails instance;

        public BalanceDetailsTests()
        {
            // TODO uncomment below to create an instance of BalanceDetails
            //instance = new BalanceDetails();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of BalanceDetails
        /// </summary>
        [Fact]
        public void BalanceDetailsInstanceTest()
        {
            // TODO uncomment below to test "IsType" BalanceDetails
            //Assert.IsType<BalanceDetails>(instance);
        }

        /// <summary>
        /// Test the property 'merchant_id'
        /// </summary>
        [Fact]
        public void merchant_idTest()
        {
            // TODO unit test for the property 'merchant_id'
        }

        /// <summary>
        /// Test the property 'vendor_id'
        /// </summary>
        [Fact]
        public void vendor_idTest()
        {
            // TODO unit test for the property 'vendor_id'
        }

        /// <summary>
        /// Test the property 'merchant_unsettled'
        /// </summary>
        [Fact]
        public void merchant_unsettledTest()
        {
            // TODO unit test for the property 'merchant_unsettled'
        }

        /// <summary>
        /// Test the property 'vendor_unsettled'
        /// </summary>
        [Fact]
        public void vendor_unsettledTest()
        {
            // TODO unit test for the property 'vendor_unsettled'
        }
    }
}
