/*
 * Cashfree Payment Gateway APIs
 *
 * Cashfree's Payment Gateway APIs provide developers with a streamlined pathway to integrate advanced payment processing capabilities into their applications, platforms and websites.
 *
 * The version of the OpenAPI document: 2026-01-01
 * Contact: developers@cashfree.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using cashfree-dotnet-pg-sdk.Model;
using cashfree-dotnet-pg-sdk.Client;
using System.Reflection;

namespace cashfree-dotnet-pg-sdk.Test.Model
{
    /// <summary>
    ///  Class for testing CreateSubscriptionPaymentRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CreateSubscriptionPaymentRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CreateSubscriptionPaymentRequest
        //private CreateSubscriptionPaymentRequest instance;

        public CreateSubscriptionPaymentRequestTests()
        {
            // TODO uncomment below to create an instance of CreateSubscriptionPaymentRequest
            //instance = new CreateSubscriptionPaymentRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CreateSubscriptionPaymentRequest
        /// </summary>
        [Fact]
        public void CreateSubscriptionPaymentRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" CreateSubscriptionPaymentRequest
            //Assert.IsType<CreateSubscriptionPaymentRequest>(instance);
        }

        /// <summary>
        /// Test the property 'SubscriptionId'
        /// </summary>
        [Fact]
        public void SubscriptionIdTest()
        {
            // TODO unit test for the property 'SubscriptionId'
        }

        /// <summary>
        /// Test the property 'PaymentId'
        /// </summary>
        [Fact]
        public void PaymentIdTest()
        {
            // TODO unit test for the property 'PaymentId'
        }

        /// <summary>
        /// Test the property 'PaymentType'
        /// </summary>
        [Fact]
        public void PaymentTypeTest()
        {
            // TODO unit test for the property 'PaymentType'
        }

        /// <summary>
        /// Test the property 'SubscriptionSessionId'
        /// </summary>
        [Fact]
        public void SubscriptionSessionIdTest()
        {
            // TODO unit test for the property 'SubscriptionSessionId'
        }

        /// <summary>
        /// Test the property 'PaymentAmount'
        /// </summary>
        [Fact]
        public void PaymentAmountTest()
        {
            // TODO unit test for the property 'PaymentAmount'
        }

        /// <summary>
        /// Test the property 'PaymentScheduleDate'
        /// </summary>
        [Fact]
        public void PaymentScheduleDateTest()
        {
            // TODO unit test for the property 'PaymentScheduleDate'
        }

        /// <summary>
        /// Test the property 'PaymentRemarks'
        /// </summary>
        [Fact]
        public void PaymentRemarksTest()
        {
            // TODO unit test for the property 'PaymentRemarks'
        }

        /// <summary>
        /// Test the property 'PaymentMethod'
        /// </summary>
        [Fact]
        public void PaymentMethodTest()
        {
            // TODO unit test for the property 'PaymentMethod'
        }
    }
}
