/*
 * Cashfree Payment Gateway APIs
 *
 * Cashfree's Payment Gateway APIs provide developers with a streamlined pathway to integrate advanced payment processing capabilities into their applications, platforms and websites.
 *
 * The version of the OpenAPI document: 2026-01-01
 * Contact: developers@cashfree.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using cashfree-dotnet-pg-sdk.Model;
using cashfree-dotnet-pg-sdk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace cashfree-dotnet-pg-sdk.Test.Model
{
    /// <summary>
    ///  Class for testing CreateSubscriptionPaymentRequestPaymentMethod
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CreateSubscriptionPaymentRequestPaymentMethodTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CreateSubscriptionPaymentRequestPaymentMethod
        //private CreateSubscriptionPaymentRequestPaymentMethod instance;

        public CreateSubscriptionPaymentRequestPaymentMethodTests()
        {
            // TODO uncomment below to create an instance of CreateSubscriptionPaymentRequestPaymentMethod
            //instance = new CreateSubscriptionPaymentRequestPaymentMethod();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CreateSubscriptionPaymentRequestPaymentMethod
        /// </summary>
        [Fact]
        public void CreateSubscriptionPaymentRequestPaymentMethodInstanceTest()
        {
            // TODO uncomment below to test "IsType" CreateSubscriptionPaymentRequestPaymentMethod
            //Assert.IsType<CreateSubscriptionPaymentRequestPaymentMethod>(instance);
        }

        /// <summary>
        /// Test the property 'upi'
        /// </summary>
        [Fact]
        public void upiTest()
        {
            // TODO unit test for the property 'upi'
        }

        /// <summary>
        /// Test the property 'enach'
        /// </summary>
        [Fact]
        public void enachTest()
        {
            // TODO unit test for the property 'enach'
        }

        /// <summary>
        /// Test the property 'pnach'
        /// </summary>
        [Fact]
        public void pnachTest()
        {
            // TODO unit test for the property 'pnach'
        }

        /// <summary>
        /// Test the property 'card'
        /// </summary>
        [Fact]
        public void cardTest()
        {
            // TODO unit test for the property 'card'
        }
    }
}
