/*
 * Cashfree Payment Gateway APIs
 *
 * Cashfree's Payment Gateway APIs provide developers with a streamlined pathway to integrate advanced payment processing capabilities into their applications, platforms and websites.
 *
 * The version of the OpenAPI document: 2026-01-01
 * Contact: developers@cashfree.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using cashfree-dotnet-pg-sdk.Model;
using cashfree-dotnet-pg-sdk.Client;
using System.Reflection;

namespace cashfree-dotnet-pg-sdk.Test.Model
{
    /// <summary>
    ///  Class for testing CreateVendorResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CreateVendorResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CreateVendorResponse
        //private CreateVendorResponse instance;

        public CreateVendorResponseTests()
        {
            // TODO uncomment below to create an instance of CreateVendorResponse
            //instance = new CreateVendorResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CreateVendorResponse
        /// </summary>
        [Fact]
        public void CreateVendorResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" CreateVendorResponse
            //Assert.IsType<CreateVendorResponse>(instance);
        }

        /// <summary>
        /// Test the property 'Email'
        /// </summary>
        [Fact]
        public void EmailTest()
        {
            // TODO unit test for the property 'Email'
        }

        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Fact]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }

        /// <summary>
        /// Test the property 'Bank'
        /// </summary>
        [Fact]
        public void BankTest()
        {
            // TODO unit test for the property 'Bank'
        }

        /// <summary>
        /// Test the property 'Upi'
        /// </summary>
        [Fact]
        public void UpiTest()
        {
            // TODO unit test for the property 'Upi'
        }

        /// <summary>
        /// Test the property 'Phone'
        /// </summary>
        [Fact]
        public void PhoneTest()
        {
            // TODO unit test for the property 'Phone'
        }

        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }

        /// <summary>
        /// Test the property 'VendorId'
        /// </summary>
        [Fact]
        public void VendorIdTest()
        {
            // TODO unit test for the property 'VendorId'
        }

        /// <summary>
        /// Test the property 'ScheduleOption'
        /// </summary>
        [Fact]
        public void ScheduleOptionTest()
        {
            // TODO unit test for the property 'ScheduleOption'
        }

        /// <summary>
        /// Test the property 'KycDetails'
        /// </summary>
        [Fact]
        public void KycDetailsTest()
        {
            // TODO unit test for the property 'KycDetails'
        }

        /// <summary>
        /// Test the property 'DashboardAccess'
        /// </summary>
        [Fact]
        public void DashboardAccessTest()
        {
            // TODO unit test for the property 'DashboardAccess'
        }

        /// <summary>
        /// Test the property 'BankDetails'
        /// </summary>
        [Fact]
        public void BankDetailsTest()
        {
            // TODO unit test for the property 'BankDetails'
        }
    }
}
