/*
 * Cashfree Payment Gateway APIs
 *
 * Cashfree's Payment Gateway APIs provide developers with a streamlined pathway to integrate advanced payment processing capabilities into their applications, platforms and websites.
 *
 * The version of the OpenAPI document: 2026-01-01
 * Contact: developers@cashfree.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using cashfree-dotnet-pg-sdk.Model;
using cashfree-dotnet-pg-sdk.Client;
using System.Reflection;

namespace cashfree-dotnet-pg-sdk.Test.Model
{
    /// <summary>
    ///  Class for testing CreateOrderSettlementRequestBodyMetaData
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CreateOrderSettlementRequestBodyMetaDataTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CreateOrderSettlementRequestBodyMetaData
        //private CreateOrderSettlementRequestBodyMetaData instance;

        public CreateOrderSettlementRequestBodyMetaDataTests()
        {
            // TODO uncomment below to create an instance of CreateOrderSettlementRequestBodyMetaData
            //instance = new CreateOrderSettlementRequestBodyMetaData();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CreateOrderSettlementRequestBodyMetaData
        /// </summary>
        [Fact]
        public void CreateOrderSettlementRequestBodyMetaDataInstanceTest()
        {
            // TODO uncomment below to test "IsType" CreateOrderSettlementRequestBodyMetaData
            //Assert.IsType<CreateOrderSettlementRequestBodyMetaData>(instance);
        }

        /// <summary>
        /// Test the property 'CbriksId'
        /// </summary>
        [Fact]
        public void CbriksIdTest()
        {
            // TODO unit test for the property 'CbriksId'
        }

        /// <summary>
        /// Test the property 'SettlementDate'
        /// </summary>
        [Fact]
        public void SettlementDateTest()
        {
            // TODO unit test for the property 'SettlementDate'
        }
    }
}
