/*
 * Cashfree Payment Gateway APIs
 *
 * Cashfree's Payment Gateway APIs provide developers with a streamlined pathway to integrate advanced payment processing capabilities into their applications, platforms and websites.
 *
 * The version of the OpenAPI document: 2026-01-01
 * Contact: developers@cashfree.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using cashfree-dotnet-pg-sdk.Model;
using cashfree-dotnet-pg-sdk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace cashfree-dotnet-pg-sdk.Test.Model
{
    /// <summary>
    ///  Class for testing CreateSubscriptionRequestPlanDetails
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CreateSubscriptionRequestPlanDetailsTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CreateSubscriptionRequestPlanDetails
        //private CreateSubscriptionRequestPlanDetails instance;

        public CreateSubscriptionRequestPlanDetailsTests()
        {
            // TODO uncomment below to create an instance of CreateSubscriptionRequestPlanDetails
            //instance = new CreateSubscriptionRequestPlanDetails();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CreateSubscriptionRequestPlanDetails
        /// </summary>
        [Fact]
        public void CreateSubscriptionRequestPlanDetailsInstanceTest()
        {
            // TODO uncomment below to test "IsType" CreateSubscriptionRequestPlanDetails
            //Assert.IsType<CreateSubscriptionRequestPlanDetails>(instance);
        }

        /// <summary>
        /// Test the property 'plan_id'
        /// </summary>
        [Fact]
        public void plan_idTest()
        {
            // TODO unit test for the property 'plan_id'
        }

        /// <summary>
        /// Test the property 'plan_name'
        /// </summary>
        [Fact]
        public void plan_nameTest()
        {
            // TODO unit test for the property 'plan_name'
        }

        /// <summary>
        /// Test the property 'plan_type'
        /// </summary>
        [Fact]
        public void plan_typeTest()
        {
            // TODO unit test for the property 'plan_type'
        }

        /// <summary>
        /// Test the property 'plan_currency'
        /// </summary>
        [Fact]
        public void plan_currencyTest()
        {
            // TODO unit test for the property 'plan_currency'
        }

        /// <summary>
        /// Test the property 'plan_amount'
        /// </summary>
        [Fact]
        public void plan_amountTest()
        {
            // TODO unit test for the property 'plan_amount'
        }

        /// <summary>
        /// Test the property 'plan_max_amount'
        /// </summary>
        [Fact]
        public void plan_max_amountTest()
        {
            // TODO unit test for the property 'plan_max_amount'
        }

        /// <summary>
        /// Test the property 'plan_max_cycles'
        /// </summary>
        [Fact]
        public void plan_max_cyclesTest()
        {
            // TODO unit test for the property 'plan_max_cycles'
        }

        /// <summary>
        /// Test the property 'plan_intervals'
        /// </summary>
        [Fact]
        public void plan_intervalsTest()
        {
            // TODO unit test for the property 'plan_intervals'
        }

        /// <summary>
        /// Test the property 'plan_interval_type'
        /// </summary>
        [Fact]
        public void plan_interval_typeTest()
        {
            // TODO unit test for the property 'plan_interval_type'
        }

        /// <summary>
        /// Test the property 'plan_note'
        /// </summary>
        [Fact]
        public void plan_noteTest()
        {
            // TODO unit test for the property 'plan_note'
        }
    }
}
