/*
 * Cashfree Payment Gateway APIs
 *
 * Cashfree's Payment Gateway APIs provide developers with a streamlined pathway to integrate advanced payment processing capabilities into their applications, platforms and websites.
 *
 * The version of the OpenAPI document: 2026-01-01
 * Contact: developers@cashfree.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using cashfree-dotnet-pg-sdk.Model;
using cashfree-dotnet-pg-sdk.Client;
using System.Reflection;

namespace cashfree-dotnet-pg-sdk.Test.Model
{
    /// <summary>
    ///  Class for testing DiscountDetails
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class DiscountDetailsTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for DiscountDetails
        //private DiscountDetails instance;

        public DiscountDetailsTests()
        {
            // TODO uncomment below to create an instance of DiscountDetails
            //instance = new DiscountDetails();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of DiscountDetails
        /// </summary>
        [Fact]
        public void DiscountDetailsInstanceTest()
        {
            // TODO uncomment below to test "IsType" DiscountDetails
            //Assert.IsType<DiscountDetails>(instance);
        }

        /// <summary>
        /// Test the property 'DiscountType'
        /// </summary>
        [Fact]
        public void DiscountTypeTest()
        {
            // TODO unit test for the property 'DiscountType'
        }

        /// <summary>
        /// Test the property 'DiscountValue'
        /// </summary>
        [Fact]
        public void DiscountValueTest()
        {
            // TODO unit test for the property 'DiscountValue'
        }

        /// <summary>
        /// Test the property 'MaxDiscountAmount'
        /// </summary>
        [Fact]
        public void MaxDiscountAmountTest()
        {
            // TODO unit test for the property 'MaxDiscountAmount'
        }
    }
}
