/*
 * Cashfree Payment Gateway APIs
 *
 * Cashfree's Payment Gateway APIs provide developers with a streamlined pathway to integrate advanced payment processing capabilities into their applications, platforms and websites.
 *
 * The version of the OpenAPI document: 2026-01-01
 * Contact: developers@cashfree.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using cashfree-dotnet-pg-sdk.Model;
using cashfree-dotnet-pg-sdk.Client;
using System.Reflection;

namespace cashfree-dotnet-pg-sdk.Test.Model
{
    /// <summary>
    ///  Class for testing EligibilityFetchOffersRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class EligibilityFetchOffersRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for EligibilityFetchOffersRequest
        //private EligibilityFetchOffersRequest instance;

        public EligibilityFetchOffersRequestTests()
        {
            // TODO uncomment below to create an instance of EligibilityFetchOffersRequest
            //instance = new EligibilityFetchOffersRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of EligibilityFetchOffersRequest
        /// </summary>
        [Fact]
        public void EligibilityFetchOffersRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" EligibilityFetchOffersRequest
            //Assert.IsType<EligibilityFetchOffersRequest>(instance);
        }

        /// <summary>
        /// Test the property 'Queries'
        /// </summary>
        [Fact]
        public void QueriesTest()
        {
            // TODO unit test for the property 'Queries'
        }

        /// <summary>
        /// Test the property 'Filters'
        /// </summary>
        [Fact]
        public void FiltersTest()
        {
            // TODO unit test for the property 'Filters'
        }
    }
}
