/*
 * Cashfree Payment Gateway APIs
 *
 * Cashfree's Payment Gateway APIs provide developers with a streamlined pathway to integrate advanced payment processing capabilities into their applications, platforms and websites.
 *
 * The version of the OpenAPI document: 2026-01-01
 * Contact: developers@cashfree.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using cashfree-dotnet-pg-sdk.Model;
using cashfree-dotnet-pg-sdk.Client;
using System.Reflection;

namespace cashfree-dotnet-pg-sdk.Test.Model
{
    /// <summary>
    ///  Class for testing ESOrderReconResponseDataInner
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ESOrderReconResponseDataInnerTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ESOrderReconResponseDataInner
        //private ESOrderReconResponseDataInner instance;

        public ESOrderReconResponseDataInnerTests()
        {
            // TODO uncomment below to create an instance of ESOrderReconResponseDataInner
            //instance = new ESOrderReconResponseDataInner();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ESOrderReconResponseDataInner
        /// </summary>
        [Fact]
        public void ESOrderReconResponseDataInnerInstanceTest()
        {
            // TODO uncomment below to test "IsType" ESOrderReconResponseDataInner
            //Assert.IsType<ESOrderReconResponseDataInner>(instance);
        }

        /// <summary>
        /// Test the property 'Amount'
        /// </summary>
        [Fact]
        public void AmountTest()
        {
            // TODO unit test for the property 'Amount'
        }

        /// <summary>
        /// Test the property 'SettlementEligibilityTime'
        /// </summary>
        [Fact]
        public void SettlementEligibilityTimeTest()
        {
            // TODO unit test for the property 'SettlementEligibilityTime'
        }

        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Fact]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }

        /// <summary>
        /// Test the property 'MerchantOrderId'
        /// </summary>
        [Fact]
        public void MerchantOrderIdTest()
        {
            // TODO unit test for the property 'MerchantOrderId'
        }

        /// <summary>
        /// Test the property 'TxTime'
        /// </summary>
        [Fact]
        public void TxTimeTest()
        {
            // TODO unit test for the property 'TxTime'
        }

        /// <summary>
        /// Test the property 'Settled'
        /// </summary>
        [Fact]
        public void SettledTest()
        {
            // TODO unit test for the property 'Settled'
        }

        /// <summary>
        /// Test the property 'EntityId'
        /// </summary>
        [Fact]
        public void EntityIdTest()
        {
            // TODO unit test for the property 'EntityId'
        }

        /// <summary>
        /// Test the property 'MerchantSettlementUtr'
        /// </summary>
        [Fact]
        public void MerchantSettlementUtrTest()
        {
            // TODO unit test for the property 'MerchantSettlementUtr'
        }

        /// <summary>
        /// Test the property 'Currency'
        /// </summary>
        [Fact]
        public void CurrencyTest()
        {
            // TODO unit test for the property 'Currency'
        }

        /// <summary>
        /// Test the property 'SaleType'
        /// </summary>
        [Fact]
        public void SaleTypeTest()
        {
            // TODO unit test for the property 'SaleType'
        }

        /// <summary>
        /// Test the property 'CustomerName'
        /// </summary>
        [Fact]
        public void CustomerNameTest()
        {
            // TODO unit test for the property 'CustomerName'
        }

        /// <summary>
        /// Test the property 'CustomerEmail'
        /// </summary>
        [Fact]
        public void CustomerEmailTest()
        {
            // TODO unit test for the property 'CustomerEmail'
        }

        /// <summary>
        /// Test the property 'CustomerPhone'
        /// </summary>
        [Fact]
        public void CustomerPhoneTest()
        {
            // TODO unit test for the property 'CustomerPhone'
        }

        /// <summary>
        /// Test the property 'MerchantVendorCommission'
        /// </summary>
        [Fact]
        public void MerchantVendorCommissionTest()
        {
            // TODO unit test for the property 'MerchantVendorCommission'
        }

        /// <summary>
        /// Test the property 'SplitServiceCharge'
        /// </summary>
        [Fact]
        public void SplitServiceChargeTest()
        {
            // TODO unit test for the property 'SplitServiceCharge'
        }

        /// <summary>
        /// Test the property 'SplitServiceTax'
        /// </summary>
        [Fact]
        public void SplitServiceTaxTest()
        {
            // TODO unit test for the property 'SplitServiceTax'
        }

        /// <summary>
        /// Test the property 'PgServiceTax'
        /// </summary>
        [Fact]
        public void PgServiceTaxTest()
        {
            // TODO unit test for the property 'PgServiceTax'
        }

        /// <summary>
        /// Test the property 'PgServiceCharge'
        /// </summary>
        [Fact]
        public void PgServiceChargeTest()
        {
            // TODO unit test for the property 'PgServiceCharge'
        }

        /// <summary>
        /// Test the property 'PgChargePostpaid'
        /// </summary>
        [Fact]
        public void PgChargePostpaidTest()
        {
            // TODO unit test for the property 'PgChargePostpaid'
        }

        /// <summary>
        /// Test the property 'MerchantSettlementId'
        /// </summary>
        [Fact]
        public void MerchantSettlementIdTest()
        {
            // TODO unit test for the property 'MerchantSettlementId'
        }

        /// <summary>
        /// Test the property 'AddedOn'
        /// </summary>
        [Fact]
        public void AddedOnTest()
        {
            // TODO unit test for the property 'AddedOn'
        }

        /// <summary>
        /// Test the property 'Tags'
        /// </summary>
        [Fact]
        public void TagsTest()
        {
            // TODO unit test for the property 'Tags'
        }

        /// <summary>
        /// Test the property 'EntityType'
        /// </summary>
        [Fact]
        public void EntityTypeTest()
        {
            // TODO unit test for the property 'EntityType'
        }

        /// <summary>
        /// Test the property 'SettlementInitiatedOn'
        /// </summary>
        [Fact]
        public void SettlementInitiatedOnTest()
        {
            // TODO unit test for the property 'SettlementInitiatedOn'
        }

        /// <summary>
        /// Test the property 'SettlementTime'
        /// </summary>
        [Fact]
        public void SettlementTimeTest()
        {
            // TODO unit test for the property 'SettlementTime'
        }

        /// <summary>
        /// Test the property 'OrderSplits'
        /// </summary>
        [Fact]
        public void OrderSplitsTest()
        {
            // TODO unit test for the property 'OrderSplits'
        }

        /// <summary>
        /// Test the property 'EligibleSplitBalance'
        /// </summary>
        [Fact]
        public void EligibleSplitBalanceTest()
        {
            // TODO unit test for the property 'EligibleSplitBalance'
        }
    }
}
