/*
 * Cashfree Payment Gateway APIs
 *
 * Cashfree's Payment Gateway APIs provide developers with a streamlined pathway to integrate advanced payment processing capabilities into their applications, platforms and websites.
 *
 * The version of the OpenAPI document: 2026-01-01
 * Contact: developers@cashfree.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using cashfree-dotnet-pg-sdk.Model;
using cashfree-dotnet-pg-sdk.Client;
using System.Reflection;

namespace cashfree-dotnet-pg-sdk.Test.Model
{
    /// <summary>
    ///  Class for testing GetAllTerminalTransactionRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class GetAllTerminalTransactionRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for GetAllTerminalTransactionRequest
        //private GetAllTerminalTransactionRequest instance;

        public GetAllTerminalTransactionRequestTests()
        {
            // TODO uncomment below to create an instance of GetAllTerminalTransactionRequest
            //instance = new GetAllTerminalTransactionRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of GetAllTerminalTransactionRequest
        /// </summary>
        [Fact]
        public void GetAllTerminalTransactionRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" GetAllTerminalTransactionRequest
            //Assert.IsType<GetAllTerminalTransactionRequest>(instance);
        }

        /// <summary>
        /// Test the property 'Filter'
        /// </summary>
        [Fact]
        public void FilterTest()
        {
            // TODO unit test for the property 'Filter'
        }

        /// <summary>
        /// Test the property 'Pagination'
        /// </summary>
        [Fact]
        public void PaginationTest()
        {
            // TODO unit test for the property 'Pagination'
        }
    }
}
