/*
 * Cashfree Payment Gateway APIs
 *
 * Cashfree's Payment Gateway APIs provide developers with a streamlined pathway to integrate advanced payment processing capabilities into their applications, platforms and websites.
 *
 * The version of the OpenAPI document: 2026-01-01
 * Contact: developers@cashfree.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using cashfree-dotnet-pg-sdk.Model;
using cashfree-dotnet-pg-sdk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace cashfree-dotnet-pg-sdk.Test.Model
{
    /// <summary>
    ///  Class for testing OfferExtendedDetails
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class OfferExtendedDetailsTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for OfferExtendedDetails
        //private OfferExtendedDetails instance;

        public OfferExtendedDetailsTests()
        {
            // TODO uncomment below to create an instance of OfferExtendedDetails
            //instance = new OfferExtendedDetails();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of OfferExtendedDetails
        /// </summary>
        [Fact]
        public void OfferExtendedDetailsInstanceTest()
        {
            // TODO uncomment below to test "IsType" OfferExtendedDetails
            //Assert.IsType<OfferExtendedDetails>(instance);
        }

        /// <summary>
        /// Test the property 'offer_id'
        /// </summary>
        [Fact]
        public void offer_idTest()
        {
            // TODO unit test for the property 'offer_id'
        }

        /// <summary>
        /// Test the property 'offer_status'
        /// </summary>
        [Fact]
        public void offer_statusTest()
        {
            // TODO unit test for the property 'offer_status'
        }

        /// <summary>
        /// Test the property 'offer_meta'
        /// </summary>
        [Fact]
        public void offer_metaTest()
        {
            // TODO unit test for the property 'offer_meta'
        }

        /// <summary>
        /// Test the property 'offer_tnc'
        /// </summary>
        [Fact]
        public void offer_tncTest()
        {
            // TODO unit test for the property 'offer_tnc'
        }

        /// <summary>
        /// Test the property 'offer_details'
        /// </summary>
        [Fact]
        public void offer_detailsTest()
        {
            // TODO unit test for the property 'offer_details'
        }

        /// <summary>
        /// Test the property 'offer_validations'
        /// </summary>
        [Fact]
        public void offer_validationsTest()
        {
            // TODO unit test for the property 'offer_validations'
        }
    }
}
