/*
 * Cashfree Payment Gateway APIs
 *
 * Cashfree's Payment Gateway APIs provide developers with a streamlined pathway to integrate advanced payment processing capabilities into their applications, platforms and websites.
 *
 * The version of the OpenAPI document: 2026-01-01
 * Contact: developers@cashfree.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using cashfree-dotnet-pg-sdk.Model;
using cashfree-dotnet-pg-sdk.Client;
using System.Reflection;

namespace cashfree-dotnet-pg-sdk.Test.Model
{
    /// <summary>
    ///  Class for testing OrderMetaPaymentMethodsFiltersMethods
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class OrderMetaPaymentMethodsFiltersMethodsTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for OrderMetaPaymentMethodsFiltersMethods
        //private OrderMetaPaymentMethodsFiltersMethods instance;

        public OrderMetaPaymentMethodsFiltersMethodsTests()
        {
            // TODO uncomment below to create an instance of OrderMetaPaymentMethodsFiltersMethods
            //instance = new OrderMetaPaymentMethodsFiltersMethods();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of OrderMetaPaymentMethodsFiltersMethods
        /// </summary>
        [Fact]
        public void OrderMetaPaymentMethodsFiltersMethodsInstanceTest()
        {
            // TODO uncomment below to test "IsType" OrderMetaPaymentMethodsFiltersMethods
            //Assert.IsType<OrderMetaPaymentMethodsFiltersMethods>(instance);
        }

        /// <summary>
        /// Test the property 'Action'
        /// </summary>
        [Fact]
        public void ActionTest()
        {
            // TODO unit test for the property 'Action'
        }

        /// <summary>
        /// Test the property 'Values'
        /// </summary>
        [Fact]
        public void ValuesTest()
        {
            // TODO unit test for the property 'Values'
        }
    }
}
