/*
 * Cashfree Payment Gateway APIs
 *
 * Cashfree's Payment Gateway APIs provide developers with a streamlined pathway to integrate advanced payment processing capabilities into their applications, platforms and websites.
 *
 * The version of the OpenAPI document: 2026-01-01
 * Contact: developers@cashfree.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using cashfree-dotnet-pg-sdk.Model;
using cashfree-dotnet-pg-sdk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace cashfree-dotnet-pg-sdk.Test.Model
{
    /// <summary>
    ///  Class for testing OrderUpdateRefundRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class OrderUpdateRefundRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for OrderUpdateRefundRequest
        //private OrderUpdateRefundRequest instance;

        public OrderUpdateRefundRequestTests()
        {
            // TODO uncomment below to create an instance of OrderUpdateRefundRequest
            //instance = new OrderUpdateRefundRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of OrderUpdateRefundRequest
        /// </summary>
        [Fact]
        public void OrderUpdateRefundRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" OrderUpdateRefundRequest
            //Assert.IsType<OrderUpdateRefundRequest>(instance);
        }

        /// <summary>
        /// Test the property 'refund_status'
        /// </summary>
        [Fact]
        public void refund_statusTest()
        {
            // TODO unit test for the property 'refund_status'
        }

        /// <summary>
        /// Test the property 'remarks'
        /// </summary>
        [Fact]
        public void remarksTest()
        {
            // TODO unit test for the property 'remarks'
        }
    }
}
