/*
 * Cashfree Payment Gateway APIs
 *
 * Cashfree's Payment Gateway APIs provide developers with a streamlined pathway to integrate advanced payment processing capabilities into their applications, platforms and websites.
 *
 * The version of the OpenAPI document: 2026-01-01
 * Contact: developers@cashfree.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using cashfree-dotnet-pg-sdk.Model;
using cashfree-dotnet-pg-sdk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace cashfree-dotnet-pg-sdk.Test.Model
{
    /// <summary>
    ///  Class for testing PaymentMethodNetBankingInPaymentsEntityNetbanking
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PaymentMethodNetBankingInPaymentsEntityNetbankingTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for PaymentMethodNetBankingInPaymentsEntityNetbanking
        //private PaymentMethodNetBankingInPaymentsEntityNetbanking instance;

        public PaymentMethodNetBankingInPaymentsEntityNetbankingTests()
        {
            // TODO uncomment below to create an instance of PaymentMethodNetBankingInPaymentsEntityNetbanking
            //instance = new PaymentMethodNetBankingInPaymentsEntityNetbanking();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PaymentMethodNetBankingInPaymentsEntityNetbanking
        /// </summary>
        [Fact]
        public void PaymentMethodNetBankingInPaymentsEntityNetbankingInstanceTest()
        {
            // TODO uncomment below to test "IsType" PaymentMethodNetBankingInPaymentsEntityNetbanking
            //Assert.IsType<PaymentMethodNetBankingInPaymentsEntityNetbanking>(instance);
        }

        /// <summary>
        /// Test the property 'channel'
        /// </summary>
        [Fact]
        public void channelTest()
        {
            // TODO unit test for the property 'channel'
        }

        /// <summary>
        /// Test the property 'netbanking_bank_code'
        /// </summary>
        [Fact]
        public void netbanking_bank_codeTest()
        {
            // TODO unit test for the property 'netbanking_bank_code'
        }

        /// <summary>
        /// Test the property 'netbanking_bank_name'
        /// </summary>
        [Fact]
        public void netbanking_bank_nameTest()
        {
            // TODO unit test for the property 'netbanking_bank_name'
        }

        /// <summary>
        /// Test the property 'netbanking_ifsc'
        /// </summary>
        [Fact]
        public void netbanking_ifscTest()
        {
            // TODO unit test for the property 'netbanking_ifsc'
        }

        /// <summary>
        /// Test the property 'netbanking_account_number'
        /// </summary>
        [Fact]
        public void netbanking_account_numberTest()
        {
            // TODO unit test for the property 'netbanking_account_number'
        }
    }
}
