/*
 * Cashfree Payment Gateway APIs
 *
 * Cashfree's Payment Gateway APIs provide developers with a streamlined pathway to integrate advanced payment processing capabilities into their applications, platforms and websites.
 *
 * The version of the OpenAPI document: 2026-01-01
 * Contact: developers@cashfree.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using cashfree-dotnet-pg-sdk.Model;
using cashfree-dotnet-pg-sdk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace cashfree-dotnet-pg-sdk.Test.Model
{
    /// <summary>
    ///  Class for testing PaymentWebhook
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PaymentWebhookTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for PaymentWebhook
        //private PaymentWebhook instance;

        public PaymentWebhookTests()
        {
            // TODO uncomment below to create an instance of PaymentWebhook
            //instance = new PaymentWebhook();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PaymentWebhook
        /// </summary>
        [Fact]
        public void PaymentWebhookInstanceTest()
        {
            // TODO uncomment below to test "IsType" PaymentWebhook
            //Assert.IsType<PaymentWebhook>(instance);
        }

        /// <summary>
        /// Test the property 'data'
        /// </summary>
        [Fact]
        public void dataTest()
        {
            // TODO unit test for the property 'data'
        }

        /// <summary>
        /// Test the property 'event_time'
        /// </summary>
        [Fact]
        public void event_timeTest()
        {
            // TODO unit test for the property 'event_time'
        }

        /// <summary>
        /// Test the property 'type'
        /// </summary>
        [Fact]
        public void typeTest()
        {
            // TODO unit test for the property 'type'
        }
    }
}
