/*
 * Cashfree Payment Gateway APIs
 *
 * Cashfree's Payment Gateway APIs provide developers with a streamlined pathway to integrate advanced payment processing capabilities into their applications, platforms and websites.
 *
 * The version of the OpenAPI document: 2026-01-01
 * Contact: developers@cashfree.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using cashfree-dotnet-pg-sdk.Model;
using cashfree-dotnet-pg-sdk.Client;
using System.Reflection;

namespace cashfree-dotnet-pg-sdk.Test.Model
{
    /// <summary>
    ///  Class for testing PaymentWebhookGatewayDetailsEntity
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PaymentWebhookGatewayDetailsEntityTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for PaymentWebhookGatewayDetailsEntity
        //private PaymentWebhookGatewayDetailsEntity instance;

        public PaymentWebhookGatewayDetailsEntityTests()
        {
            // TODO uncomment below to create an instance of PaymentWebhookGatewayDetailsEntity
            //instance = new PaymentWebhookGatewayDetailsEntity();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PaymentWebhookGatewayDetailsEntity
        /// </summary>
        [Fact]
        public void PaymentWebhookGatewayDetailsEntityInstanceTest()
        {
            // TODO uncomment below to test "IsType" PaymentWebhookGatewayDetailsEntity
            //Assert.IsType<PaymentWebhookGatewayDetailsEntity>(instance);
        }

        /// <summary>
        /// Test the property 'GatewayName'
        /// </summary>
        [Fact]
        public void GatewayNameTest()
        {
            // TODO unit test for the property 'GatewayName'
        }

        /// <summary>
        /// Test the property 'GatewayOrderId'
        /// </summary>
        [Fact]
        public void GatewayOrderIdTest()
        {
            // TODO unit test for the property 'GatewayOrderId'
        }

        /// <summary>
        /// Test the property 'GatewayOrderReferenceId'
        /// </summary>
        [Fact]
        public void GatewayOrderReferenceIdTest()
        {
            // TODO unit test for the property 'GatewayOrderReferenceId'
        }

        /// <summary>
        /// Test the property 'GatewayPaymentId'
        /// </summary>
        [Fact]
        public void GatewayPaymentIdTest()
        {
            // TODO unit test for the property 'GatewayPaymentId'
        }

        /// <summary>
        /// Test the property 'GatewayStatusCode'
        /// </summary>
        [Fact]
        public void GatewayStatusCodeTest()
        {
            // TODO unit test for the property 'GatewayStatusCode'
        }

        /// <summary>
        /// Test the property 'GatewaySettlement'
        /// </summary>
        [Fact]
        public void GatewaySettlementTest()
        {
            // TODO unit test for the property 'GatewaySettlement'
        }

        /// <summary>
        /// Test the property 'GatewayReferenceName'
        /// </summary>
        [Fact]
        public void GatewayReferenceNameTest()
        {
            // TODO unit test for the property 'GatewayReferenceName'
        }
    }
}
