/*
 * Cashfree Payment Gateway APIs
 *
 * Cashfree's Payment Gateway APIs provide developers with a streamlined pathway to integrate advanced payment processing capabilities into their applications, platforms and websites.
 *
 * The version of the OpenAPI document: 2026-01-01
 * Contact: developers@cashfree.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using cashfree-dotnet-pg-sdk.Model;
using cashfree-dotnet-pg-sdk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace cashfree-dotnet-pg-sdk.Test.Model
{
    /// <summary>
    ///  Class for testing PaymentLinkOrderEntity
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PaymentLinkOrderEntityTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for PaymentLinkOrderEntity
        //private PaymentLinkOrderEntity instance;

        public PaymentLinkOrderEntityTests()
        {
            // TODO uncomment below to create an instance of PaymentLinkOrderEntity
            //instance = new PaymentLinkOrderEntity();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PaymentLinkOrderEntity
        /// </summary>
        [Fact]
        public void PaymentLinkOrderEntityInstanceTest()
        {
            // TODO uncomment below to test "IsType" PaymentLinkOrderEntity
            //Assert.IsType<PaymentLinkOrderEntity>(instance);
        }

        /// <summary>
        /// Test the property 'cf_order_id'
        /// </summary>
        [Fact]
        public void cf_order_idTest()
        {
            // TODO unit test for the property 'cf_order_id'
        }

        /// <summary>
        /// Test the property 'link_id'
        /// </summary>
        [Fact]
        public void link_idTest()
        {
            // TODO unit test for the property 'link_id'
        }

        /// <summary>
        /// Test the property 'order_id'
        /// </summary>
        [Fact]
        public void order_idTest()
        {
            // TODO unit test for the property 'order_id'
        }

        /// <summary>
        /// Test the property 'entity'
        /// </summary>
        [Fact]
        public void entityTest()
        {
            // TODO unit test for the property 'entity'
        }

        /// <summary>
        /// Test the property 'order_currency'
        /// </summary>
        [Fact]
        public void order_currencyTest()
        {
            // TODO unit test for the property 'order_currency'
        }

        /// <summary>
        /// Test the property 'order_amount'
        /// </summary>
        [Fact]
        public void order_amountTest()
        {
            // TODO unit test for the property 'order_amount'
        }

        /// <summary>
        /// Test the property 'order_status'
        /// </summary>
        [Fact]
        public void order_statusTest()
        {
            // TODO unit test for the property 'order_status'
        }

        /// <summary>
        /// Test the property 'payment_session_id'
        /// </summary>
        [Fact]
        public void payment_session_idTest()
        {
            // TODO unit test for the property 'payment_session_id'
        }

        /// <summary>
        /// Test the property 'order_expiry_time'
        /// </summary>
        [Fact]
        public void order_expiry_timeTest()
        {
            // TODO unit test for the property 'order_expiry_time'
        }

        /// <summary>
        /// Test the property 'order_note'
        /// </summary>
        [Fact]
        public void order_noteTest()
        {
            // TODO unit test for the property 'order_note'
        }

        /// <summary>
        /// Test the property 'created_at'
        /// </summary>
        [Fact]
        public void created_atTest()
        {
            // TODO unit test for the property 'created_at'
        }

        /// <summary>
        /// Test the property 'order_splits'
        /// </summary>
        [Fact]
        public void order_splitsTest()
        {
            // TODO unit test for the property 'order_splits'
        }

        /// <summary>
        /// Test the property 'customer_details'
        /// </summary>
        [Fact]
        public void customer_detailsTest()
        {
            // TODO unit test for the property 'customer_details'
        }

        /// <summary>
        /// Test the property 'order_meta'
        /// </summary>
        [Fact]
        public void order_metaTest()
        {
            // TODO unit test for the property 'order_meta'
        }

        /// <summary>
        /// Test the property 'order_tags'
        /// </summary>
        [Fact]
        public void order_tagsTest()
        {
            // TODO unit test for the property 'order_tags'
        }
    }
}
