/*
 * Cashfree Payment Gateway APIs
 *
 * Cashfree's Payment Gateway APIs provide developers with a streamlined pathway to integrate advanced payment processing capabilities into their applications, platforms and websites.
 *
 * The version of the OpenAPI document: 2026-01-01
 * Contact: developers@cashfree.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using cashfree-dotnet-pg-sdk.Model;
using cashfree-dotnet-pg-sdk.Client;
using System.Reflection;

namespace cashfree-dotnet-pg-sdk.Test.Model
{
    /// <summary>
    ///  Class for testing PGCreatePAR200Response
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PGCreatePAR200ResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for PGCreatePAR200Response
        //private PGCreatePAR200Response instance;

        public PGCreatePAR200ResponseTests()
        {
            // TODO uncomment below to create an instance of PGCreatePAR200Response
            //instance = new PGCreatePAR200Response();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PGCreatePAR200Response
        /// </summary>
        [Fact]
        public void PGCreatePAR200ResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" PGCreatePAR200Response
            //Assert.IsType<PGCreatePAR200Response>(instance);
        }

        /// <summary>
        /// Test the property 'Par'
        /// </summary>
        [Fact]
        public void ParTest()
        {
            // TODO unit test for the property 'Par'
        }
    }
}
