/*
 * Cashfree Payment Gateway APIs
 *
 * Cashfree's Payment Gateway APIs provide developers with a streamlined pathway to integrate advanced payment processing capabilities into their applications, platforms and websites.
 *
 * The version of the OpenAPI document: 2026-01-01
 * Contact: developers@cashfree.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using cashfree-dotnet-pg-sdk.Model;
using cashfree-dotnet-pg-sdk.Client;
using System.Reflection;

namespace cashfree-dotnet-pg-sdk.Test.Model
{
    /// <summary>
    ///  Class for testing ReconEntityDataInnerRefundDetails
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ReconEntityDataInnerRefundDetailsTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ReconEntityDataInnerRefundDetails
        //private ReconEntityDataInnerRefundDetails instance;

        public ReconEntityDataInnerRefundDetailsTests()
        {
            // TODO uncomment below to create an instance of ReconEntityDataInnerRefundDetails
            //instance = new ReconEntityDataInnerRefundDetails();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ReconEntityDataInnerRefundDetails
        /// </summary>
        [Fact]
        public void ReconEntityDataInnerRefundDetailsInstanceTest()
        {
            // TODO uncomment below to test "IsType" ReconEntityDataInnerRefundDetails
            //Assert.IsType<ReconEntityDataInnerRefundDetails>(instance);
        }

        /// <summary>
        /// Test the property 'RefundProcessedAt'
        /// </summary>
        [Fact]
        public void RefundProcessedAtTest()
        {
            // TODO unit test for the property 'RefundProcessedAt'
        }

        /// <summary>
        /// Test the property 'RefundArn'
        /// </summary>
        [Fact]
        public void RefundArnTest()
        {
            // TODO unit test for the property 'RefundArn'
        }

        /// <summary>
        /// Test the property 'RefundNote'
        /// </summary>
        [Fact]
        public void RefundNoteTest()
        {
            // TODO unit test for the property 'RefundNote'
        }

        /// <summary>
        /// Test the property 'RefundId'
        /// </summary>
        [Fact]
        public void RefundIdTest()
        {
            // TODO unit test for the property 'RefundId'
        }
    }
}
