/*
 * Cashfree Payment Gateway APIs
 *
 * Cashfree's Payment Gateway APIs provide developers with a streamlined pathway to integrate advanced payment processing capabilities into their applications, platforms and websites.
 *
 * The version of the OpenAPI document: 2026-01-01
 * Contact: developers@cashfree.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using cashfree-dotnet-pg-sdk.Model;
using cashfree-dotnet-pg-sdk.Client;
using System.Reflection;

namespace cashfree-dotnet-pg-sdk.Test.Model
{
    /// <summary>
    ///  Class for testing ReconEntityDataInner
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ReconEntityDataInnerTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ReconEntityDataInner
        //private ReconEntityDataInner instance;

        public ReconEntityDataInnerTests()
        {
            // TODO uncomment below to create an instance of ReconEntityDataInner
            //instance = new ReconEntityDataInner();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ReconEntityDataInner
        /// </summary>
        [Fact]
        public void ReconEntityDataInnerInstanceTest()
        {
            // TODO uncomment below to test "IsType" ReconEntityDataInner
            //Assert.IsType<ReconEntityDataInner>(instance);
        }

        /// <summary>
        /// Test the property 'EventDetails'
        /// </summary>
        [Fact]
        public void EventDetailsTest()
        {
            // TODO unit test for the property 'EventDetails'
        }

        /// <summary>
        /// Test the property 'OrderDetails'
        /// </summary>
        [Fact]
        public void OrderDetailsTest()
        {
            // TODO unit test for the property 'OrderDetails'
        }

        /// <summary>
        /// Test the property 'CustomerDetails'
        /// </summary>
        [Fact]
        public void CustomerDetailsTest()
        {
            // TODO unit test for the property 'CustomerDetails'
        }

        /// <summary>
        /// Test the property 'PaymentDetails'
        /// </summary>
        [Fact]
        public void PaymentDetailsTest()
        {
            // TODO unit test for the property 'PaymentDetails'
        }

        /// <summary>
        /// Test the property 'SettlementDetails'
        /// </summary>
        [Fact]
        public void SettlementDetailsTest()
        {
            // TODO unit test for the property 'SettlementDetails'
        }

        /// <summary>
        /// Test the property 'DisputeDetails'
        /// </summary>
        [Fact]
        public void DisputeDetailsTest()
        {
            // TODO unit test for the property 'DisputeDetails'
        }

        /// <summary>
        /// Test the property 'RefundDetails'
        /// </summary>
        [Fact]
        public void RefundDetailsTest()
        {
            // TODO unit test for the property 'RefundDetails'
        }
    }
}
