/*
 * Cashfree Payment Gateway APIs
 *
 * Cashfree's Payment Gateway APIs provide developers with a streamlined pathway to integrate advanced payment processing capabilities into their applications, platforms and websites.
 *
 * The version of the OpenAPI document: 2026-01-01
 * Contact: developers@cashfree.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using cashfree-dotnet-pg-sdk.Model;
using cashfree-dotnet-pg-sdk.Client;
using System.Reflection;

namespace cashfree-dotnet-pg-sdk.Test.Model
{
    /// <summary>
    ///  Class for testing RefundSpeed
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class RefundSpeedTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for RefundSpeed
        //private RefundSpeed instance;

        public RefundSpeedTests()
        {
            // TODO uncomment below to create an instance of RefundSpeed
            //instance = new RefundSpeed();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of RefundSpeed
        /// </summary>
        [Fact]
        public void RefundSpeedInstanceTest()
        {
            // TODO uncomment below to test "IsType" RefundSpeed
            //Assert.IsType<RefundSpeed>(instance);
        }

        /// <summary>
        /// Test the property 'Requested'
        /// </summary>
        [Fact]
        public void RequestedTest()
        {
            // TODO unit test for the property 'Requested'
        }

        /// <summary>
        /// Test the property 'Accepted'
        /// </summary>
        [Fact]
        public void AcceptedTest()
        {
            // TODO unit test for the property 'Accepted'
        }

        /// <summary>
        /// Test the property 'Processed'
        /// </summary>
        [Fact]
        public void ProcessedTest()
        {
            // TODO unit test for the property 'Processed'
        }

        /// <summary>
        /// Test the property 'Message'
        /// </summary>
        [Fact]
        public void MessageTest()
        {
            // TODO unit test for the property 'Message'
        }
    }
}
