/*
 * Cashfree Payment Gateway APIs
 *
 * Cashfree's Payment Gateway APIs provide developers with a streamlined pathway to integrate advanced payment processing capabilities into their applications, platforms and websites.
 *
 * The version of the OpenAPI document: 2026-01-01
 * Contact: developers@cashfree.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using cashfree-dotnet-pg-sdk.Model;
using cashfree-dotnet-pg-sdk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace cashfree-dotnet-pg-sdk.Test.Model
{
    /// <summary>
    ///  Class for testing SavedInstrumentMeta
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class SavedInstrumentMetaTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for SavedInstrumentMeta
        //private SavedInstrumentMeta instance;

        public SavedInstrumentMetaTests()
        {
            // TODO uncomment below to create an instance of SavedInstrumentMeta
            //instance = new SavedInstrumentMeta();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of SavedInstrumentMeta
        /// </summary>
        [Fact]
        public void SavedInstrumentMetaInstanceTest()
        {
            // TODO uncomment below to test "IsType" SavedInstrumentMeta
            //Assert.IsType<SavedInstrumentMeta>(instance);
        }

        /// <summary>
        /// Test the property 'card_network'
        /// </summary>
        [Fact]
        public void card_networkTest()
        {
            // TODO unit test for the property 'card_network'
        }

        /// <summary>
        /// Test the property 'card_bank_name'
        /// </summary>
        [Fact]
        public void card_bank_nameTest()
        {
            // TODO unit test for the property 'card_bank_name'
        }

        /// <summary>
        /// Test the property 'card_country'
        /// </summary>
        [Fact]
        public void card_countryTest()
        {
            // TODO unit test for the property 'card_country'
        }

        /// <summary>
        /// Test the property 'card_type'
        /// </summary>
        [Fact]
        public void card_typeTest()
        {
            // TODO unit test for the property 'card_type'
        }

        /// <summary>
        /// Test the property 'card_sub_type'
        /// </summary>
        [Fact]
        public void card_sub_typeTest()
        {
            // TODO unit test for the property 'card_sub_type'
        }

        /// <summary>
        /// Test the property 'card_token_details'
        /// </summary>
        [Fact]
        public void card_token_detailsTest()
        {
            // TODO unit test for the property 'card_token_details'
        }
    }
}
