/*
 * Cashfree Payment Gateway APIs
 *
 * Cashfree's Payment Gateway APIs provide developers with a streamlined pathway to integrate advanced payment processing capabilities into their applications, platforms and websites.
 *
 * The version of the OpenAPI document: 2026-01-01
 * Contact: developers@cashfree.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using cashfree-dotnet-pg-sdk.Model;
using cashfree-dotnet-pg-sdk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace cashfree-dotnet-pg-sdk.Test.Model
{
    /// <summary>
    ///  Class for testing SplitOrderReconSuccessResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class SplitOrderReconSuccessResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for SplitOrderReconSuccessResponse
        //private SplitOrderReconSuccessResponse instance;

        public SplitOrderReconSuccessResponseTests()
        {
            // TODO uncomment below to create an instance of SplitOrderReconSuccessResponse
            //instance = new SplitOrderReconSuccessResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of SplitOrderReconSuccessResponse
        /// </summary>
        [Fact]
        public void SplitOrderReconSuccessResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" SplitOrderReconSuccessResponse
            //Assert.IsType<SplitOrderReconSuccessResponse>(instance);
        }

        /// <summary>
        /// Test the property 'settlement'
        /// </summary>
        [Fact]
        public void settlementTest()
        {
            // TODO unit test for the property 'settlement'
        }

        /// <summary>
        /// Test the property 'refunds'
        /// </summary>
        [Fact]
        public void refundsTest()
        {
            // TODO unit test for the property 'refunds'
        }

        /// <summary>
        /// Test the property 'vendors'
        /// </summary>
        [Fact]
        public void vendorsTest()
        {
            // TODO unit test for the property 'vendors'
        }
    }
}
