/*
 * Cashfree Payment Gateway APIs
 *
 * Cashfree's Payment Gateway APIs provide developers with a streamlined pathway to integrate advanced payment processing capabilities into their applications, platforms and websites.
 *
 * The version of the OpenAPI document: 2026-01-01
 * Contact: developers@cashfree.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using cashfree-dotnet-pg-sdk.Model;
using cashfree-dotnet-pg-sdk.Client;
using System.Reflection;

namespace cashfree-dotnet-pg-sdk.Test.Model
{
    /// <summary>
    ///  Class for testing SplitAfterPaymentRequestSplitInner
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class SplitAfterPaymentRequestSplitInnerTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for SplitAfterPaymentRequestSplitInner
        //private SplitAfterPaymentRequestSplitInner instance;

        public SplitAfterPaymentRequestSplitInnerTests()
        {
            // TODO uncomment below to create an instance of SplitAfterPaymentRequestSplitInner
            //instance = new SplitAfterPaymentRequestSplitInner();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of SplitAfterPaymentRequestSplitInner
        /// </summary>
        [Fact]
        public void SplitAfterPaymentRequestSplitInnerInstanceTest()
        {
            // TODO uncomment below to test "IsType" SplitAfterPaymentRequestSplitInner
            //Assert.IsType<SplitAfterPaymentRequestSplitInner>(instance);
        }

        /// <summary>
        /// Test the property 'VendorId'
        /// </summary>
        [Fact]
        public void VendorIdTest()
        {
            // TODO unit test for the property 'VendorId'
        }

        /// <summary>
        /// Test the property 'Amount'
        /// </summary>
        [Fact]
        public void AmountTest()
        {
            // TODO unit test for the property 'Amount'
        }

        /// <summary>
        /// Test the property 'Percentage'
        /// </summary>
        [Fact]
        public void PercentageTest()
        {
            // TODO unit test for the property 'Percentage'
        }

        /// <summary>
        /// Test the property 'Tags'
        /// </summary>
        [Fact]
        public void TagsTest()
        {
            // TODO unit test for the property 'Tags'
        }
    }
}
