/*
 * Cashfree Payment Gateway APIs
 *
 * Cashfree's Payment Gateway APIs provide developers with a streamlined pathway to integrate advanced payment processing capabilities into their applications, platforms and websites.
 *
 * The version of the OpenAPI document: 2026-01-01
 * Contact: developers@cashfree.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using cashfree-dotnet-pg-sdk.Model;
using cashfree-dotnet-pg-sdk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace cashfree-dotnet-pg-sdk.Test.Model
{
    /// <summary>
    ///  Class for testing SubscriptionEntity
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class SubscriptionEntityTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for SubscriptionEntity
        //private SubscriptionEntity instance;

        public SubscriptionEntityTests()
        {
            // TODO uncomment below to create an instance of SubscriptionEntity
            //instance = new SubscriptionEntity();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of SubscriptionEntity
        /// </summary>
        [Fact]
        public void SubscriptionEntityInstanceTest()
        {
            // TODO uncomment below to test "IsType" SubscriptionEntity
            //Assert.IsType<SubscriptionEntity>(instance);
        }

        /// <summary>
        /// Test the property 'authorisation_details'
        /// </summary>
        [Fact]
        public void authorisation_detailsTest()
        {
            // TODO unit test for the property 'authorisation_details'
        }

        /// <summary>
        /// Test the property 'cf_subscription_id'
        /// </summary>
        [Fact]
        public void cf_subscription_idTest()
        {
            // TODO unit test for the property 'cf_subscription_id'
        }

        /// <summary>
        /// Test the property 'customer_details'
        /// </summary>
        [Fact]
        public void customer_detailsTest()
        {
            // TODO unit test for the property 'customer_details'
        }

        /// <summary>
        /// Test the property 'plan_details'
        /// </summary>
        [Fact]
        public void plan_detailsTest()
        {
            // TODO unit test for the property 'plan_details'
        }

        /// <summary>
        /// Test the property 'subscription_expiry_time'
        /// </summary>
        [Fact]
        public void subscription_expiry_timeTest()
        {
            // TODO unit test for the property 'subscription_expiry_time'
        }

        /// <summary>
        /// Test the property 'subscription_first_charge_time'
        /// </summary>
        [Fact]
        public void subscription_first_charge_timeTest()
        {
            // TODO unit test for the property 'subscription_first_charge_time'
        }

        /// <summary>
        /// Test the property 'subscription_id'
        /// </summary>
        [Fact]
        public void subscription_idTest()
        {
            // TODO unit test for the property 'subscription_id'
        }

        /// <summary>
        /// Test the property 'subscription_meta'
        /// </summary>
        [Fact]
        public void subscription_metaTest()
        {
            // TODO unit test for the property 'subscription_meta'
        }

        /// <summary>
        /// Test the property 'subscription_note'
        /// </summary>
        [Fact]
        public void subscription_noteTest()
        {
            // TODO unit test for the property 'subscription_note'
        }

        /// <summary>
        /// Test the property 'subscription_session_id'
        /// </summary>
        [Fact]
        public void subscription_session_idTest()
        {
            // TODO unit test for the property 'subscription_session_id'
        }

        /// <summary>
        /// Test the property 'subscription_payment_splits'
        /// </summary>
        [Fact]
        public void subscription_payment_splitsTest()
        {
            // TODO unit test for the property 'subscription_payment_splits'
        }

        /// <summary>
        /// Test the property 'subscription_status'
        /// </summary>
        [Fact]
        public void subscription_statusTest()
        {
            // TODO unit test for the property 'subscription_status'
        }

        /// <summary>
        /// Test the property 'subscription_tags'
        /// </summary>
        [Fact]
        public void subscription_tagsTest()
        {
            // TODO unit test for the property 'subscription_tags'
        }

        /// <summary>
        /// Test the property 'next_schedule_date'
        /// </summary>
        [Fact]
        public void next_schedule_dateTest()
        {
            // TODO unit test for the property 'next_schedule_date'
        }
    }
}
