/*
 * Cashfree Payment Gateway APIs
 *
 * Cashfree's Payment Gateway APIs provide developers with a streamlined pathway to integrate advanced payment processing capabilities into their applications, platforms and websites.
 *
 * The version of the OpenAPI document: 2026-01-01
 * Contact: developers@cashfree.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using cashfree-dotnet-pg-sdk.Model;
using cashfree-dotnet-pg-sdk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace cashfree-dotnet-pg-sdk.Test.Model
{
    /// <summary>
    ///  Class for testing UpdateTerminalStatusRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class UpdateTerminalStatusRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for UpdateTerminalStatusRequest
        //private UpdateTerminalStatusRequest instance;

        public UpdateTerminalStatusRequestTests()
        {
            // TODO uncomment below to create an instance of UpdateTerminalStatusRequest
            //instance = new UpdateTerminalStatusRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of UpdateTerminalStatusRequest
        /// </summary>
        [Fact]
        public void UpdateTerminalStatusRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" UpdateTerminalStatusRequest
            //Assert.IsType<UpdateTerminalStatusRequest>(instance);
        }

        /// <summary>
        /// Test the property 'terminal_status'
        /// </summary>
        [Fact]
        public void terminal_statusTest()
        {
            // TODO unit test for the property 'terminal_status'
        }
    }
}
