/*
 * Cashfree Payment Gateway APIs
 *
 * Cashfree's Payment Gateway APIs provide developers with a streamlined pathway to integrate advanced payment processing capabilities into their applications, platforms and websites.
 *
 * The version of the OpenAPI document: 2026-01-01
 * Contact: developers@cashfree.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using cashfree-dotnet-pg-sdk.Model;
using cashfree-dotnet-pg-sdk.Client;
using System.Reflection;

namespace cashfree-dotnet-pg-sdk.Test.Model
{
    /// <summary>
    ///  Class for testing UpdateSoundboxVpaRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class UpdateSoundboxVpaRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for UpdateSoundboxVpaRequest
        //private UpdateSoundboxVpaRequest instance;

        public UpdateSoundboxVpaRequestTests()
        {
            // TODO uncomment below to create an instance of UpdateSoundboxVpaRequest
            //instance = new UpdateSoundboxVpaRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of UpdateSoundboxVpaRequest
        /// </summary>
        [Fact]
        public void UpdateSoundboxVpaRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" UpdateSoundboxVpaRequest
            //Assert.IsType<UpdateSoundboxVpaRequest>(instance);
        }

        /// <summary>
        /// Test the property 'Vpa'
        /// </summary>
        [Fact]
        public void VpaTest()
        {
            // TODO unit test for the property 'Vpa'
        }

        /// <summary>
        /// Test the property 'CfTerminalId'
        /// </summary>
        [Fact]
        public void CfTerminalIdTest()
        {
            // TODO unit test for the property 'CfTerminalId'
        }

        /// <summary>
        /// Test the property 'MerchantName'
        /// </summary>
        [Fact]
        public void MerchantNameTest()
        {
            // TODO unit test for the property 'MerchantName'
        }

        /// <summary>
        /// Test the property 'Language'
        /// </summary>
        [Fact]
        public void LanguageTest()
        {
            // TODO unit test for the property 'Language'
        }
    }
}
