/*
 * Cashfree Payment Gateway APIs
 *
 * Cashfree's Payment Gateway APIs provide developers with a streamlined pathway to integrate advanced payment processing capabilities into their applications, platforms and websites.
 *
 * The version of the OpenAPI document: 2026-01-01
 * Contact: developers@cashfree.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using cashfree-dotnet-pg-sdk.Model;
using cashfree-dotnet-pg-sdk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace cashfree-dotnet-pg-sdk.Test.Model
{
    /// <summary>
    ///  Class for testing UPIPaymentMethod
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class UPIPaymentMethodTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for UPIPaymentMethod
        //private UPIPaymentMethod instance;

        public UPIPaymentMethodTests()
        {
            // TODO uncomment below to create an instance of UPIPaymentMethod
            //instance = new UPIPaymentMethod();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of UPIPaymentMethod
        /// </summary>
        [Fact]
        public void UPIPaymentMethodInstanceTest()
        {
            // TODO uncomment below to test "IsType" UPIPaymentMethod
            //Assert.IsType<UPIPaymentMethod>(instance);
        }

        /// <summary>
        /// Test the property 'upi'
        /// </summary>
        [Fact]
        public void upiTest()
        {
            // TODO unit test for the property 'upi'
        }
    }
}
