/*
 * Cashfree Payment Gateway APIs
 *
 * Cashfree's Payment Gateway APIs provide developers with a streamlined pathway to integrate advanced payment processing capabilities into their applications, platforms and websites.
 *
 * The version of the OpenAPI document: 2026-01-01
 * Contact: developers@cashfree.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using cashfree-dotnet-pg-sdk.Model;
using cashfree-dotnet-pg-sdk.Client;
using System.Reflection;

namespace cashfree-dotnet-pg-sdk.Test.Model
{
    /// <summary>
    ///  Class for testing UploadTerminalDocsEntity
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class UploadTerminalDocsEntityTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for UploadTerminalDocsEntity
        //private UploadTerminalDocsEntity instance;

        public UploadTerminalDocsEntityTests()
        {
            // TODO uncomment below to create an instance of UploadTerminalDocsEntity
            //instance = new UploadTerminalDocsEntity();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of UploadTerminalDocsEntity
        /// </summary>
        [Fact]
        public void UploadTerminalDocsEntityInstanceTest()
        {
            // TODO uncomment below to test "IsType" UploadTerminalDocsEntity
            //Assert.IsType<UploadTerminalDocsEntity>(instance);
        }

        /// <summary>
        /// Test the property 'CfTerminalId'
        /// </summary>
        [Fact]
        public void CfTerminalIdTest()
        {
            // TODO unit test for the property 'CfTerminalId'
        }

        /// <summary>
        /// Test the property 'DocType'
        /// </summary>
        [Fact]
        public void DocTypeTest()
        {
            // TODO unit test for the property 'DocType'
        }

        /// <summary>
        /// Test the property 'DocValue'
        /// </summary>
        [Fact]
        public void DocValueTest()
        {
            // TODO unit test for the property 'DocValue'
        }

        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Fact]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }
    }
}
