/*
 * Cashfree Payment Gateway APIs
 *
 * Cashfree's Payment Gateway APIs provide developers with a streamlined pathway to integrate advanced payment processing capabilities into their applications, platforms and websites.
 *
 * The version of the OpenAPI document: 2026-01-01
 * Contact: developers@cashfree.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = cashfree_pg.Client.OpenAPIDateConverter;

namespace cashfree_pg.Model
{
    /// <summary>
    /// Request body to create a terminal transaction.
    /// </summary>
    [DataContract(Name = "CreateTerminalTransactionRequest")]
    public class CreateTerminalTransactionRequest : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CreateTerminalTransactionRequest" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected CreateTerminalTransactionRequest() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="CreateTerminalTransactionRequest" /> class.
        /// </summary>
        /// <param name="">cashfree order ID that was returned while creating an order. (required).</param>
        /// <param name="">Cashfree terminal ID, this is a required parameter when you do not provide the terminal phone number..</param>
        /// <param name="">mention the payment method used for the transaction. possible values - QR_CODE, LINK..</param>
        /// <param name="">agent mobile number assigned to the terminal. this is a required parameter when you do not provide the cf_terminal_id..</param>
        /// <param name="">make it true to have request be sent to create a Dynamic GST QR Code..</param>
        public CreateTerminalTransactionRequest(string  = default(string), long?  = default(long?), string?  = default(string?), string?  = default(string?), bool?  = default(bool?))
        {
            // to ensure "" is required (not null)
            if ( == null)
            {
                throw new ArgumentNullException(" is a required property for CreateTerminalTransactionRequest and cannot be null");
            }
            this.cf_order_id = ;
            this.cf_terminal_id = ;
            this.payment_method = ;
            this.terminal_phone_no = ;
            this.add_invoice = ;
        }

        /// <summary>
        /// cashfree order ID that was returned while creating an order.
        /// </summary>
        /// <value>cashfree order ID that was returned while creating an order.</value>
        [DataMember(Name = "cf_order_id", IsRequired = true, EmitDefaultValue = true)]
        public string cf_order_id { get; set; }

        /// <summary>
        /// Cashfree terminal ID, this is a required parameter when you do not provide the terminal phone number.
        /// </summary>
        /// <value>Cashfree terminal ID, this is a required parameter when you do not provide the terminal phone number.</value>
        [DataMember(Name = "cf_terminal_id", EmitDefaultValue = false)]
        public long? cf_terminal_id { get; set; }

        /// <summary>
        /// mention the payment method used for the transaction. possible values - QR_CODE, LINK.
        /// </summary>
        /// <value>mention the payment method used for the transaction. possible values - QR_CODE, LINK.</value>
        [DataMember(Name = "payment_method", EmitDefaultValue = false)]
        public string? payment_method { get; set; }

        /// <summary>
        /// agent mobile number assigned to the terminal. this is a required parameter when you do not provide the cf_terminal_id.
        /// </summary>
        /// <value>agent mobile number assigned to the terminal. this is a required parameter when you do not provide the cf_terminal_id.</value>
        [DataMember(Name = "terminal_phone_no", EmitDefaultValue = false)]
        public string? terminal_phone_no { get; set; }

        /// <summary>
        /// make it true to have request be sent to create a Dynamic GST QR Code.
        /// </summary>
        /// <value>make it true to have request be sent to create a Dynamic GST QR Code.</value>
        [DataMember(Name = "add_invoice", EmitDefaultValue = true)]
        public bool? add_invoice { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class CreateTerminalTransactionRequest {\n");
            sb.Append("  cf_order_id: ").Append(cf_order_id).Append("\n");
            sb.Append("  cf_terminal_id: ").Append(cf_terminal_id).Append("\n");
            sb.Append("  payment_method: ").Append(payment_method).Append("\n");
            sb.Append("  terminal_phone_no: ").Append(terminal_phone_no).Append("\n");
            sb.Append("  add_invoice: ").Append(add_invoice).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // payment_method (string) maxLength
            if (this.payment_method != null && this.payment_method.Length > 100)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for payment_method, length must be less than 100.", new [] { "payment_method" });
            }

            // payment_method (string) minLength
            if (this.payment_method != null && this.payment_method.Length < 3)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for payment_method, length must be greater than 3.", new [] { "payment_method" });
            }

            // terminal_phone_no (string) maxLength
            if (this.terminal_phone_no != null && this.terminal_phone_no.Length > 10)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for terminal_phone_no, length must be less than 10.", new [] { "terminal_phone_no" });
            }

            // terminal_phone_no (string) minLength
            if (this.terminal_phone_no != null && this.terminal_phone_no.Length < 10)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for terminal_phone_no, length must be greater than 10.", new [] { "terminal_phone_no" });
            }

            yield break;
        }    }

}
