/*
 * Cashfree Payment Gateway APIs
 *
 * Cashfree's Payment Gateway APIs provide developers with a streamlined pathway to integrate advanced payment processing capabilities into their applications, platforms and websites.
 *
 * The version of the OpenAPI document: 2026-01-01
 * Contact: developers@cashfree.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = cashfree_pg.Client.OpenAPIDateConverter;

namespace cashfree_pg.Model
{
    /// <summary>
    /// Delete saved card instrument object.
    /// </summary>
    [DataContract(Name = "DeletedInstrumentEntity")]
    public class DeletedInstrumentEntity : IValidatableObject
    {
        /// <summary>
        /// Type of the saved instrument.
        /// </summary>
        /// <value>Type of the saved instrument.</value>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum InstrumentTypeEnum
        {
            /// <summary>
            /// Enum Card for value: card
            /// </summary>
            [EnumMember(Value = "card")]
            Card = 1
        }

        /// <summary>
        /// Type of the saved instrument.
        /// </summary>
        /// <value>Type of the saved instrument.</value>
        [DataMember(Name = "instrument_type", EmitDefaultValue = false)]
        public InstrumentTypeEnum? instrument_type { get; set; }
        /// <summary>
        /// Status of the saved instrument. This would be &#x60;INACTIVE&#x60; when the instrument is successfully deleted.
        /// </summary>
        /// <value>Status of the saved instrument. This would be &#x60;INACTIVE&#x60; when the instrument is successfully deleted.</value>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum InstrumentStatusEnum
        {
            /// <summary>
            /// Enum INACTIVE for value: INACTIVE
            /// </summary>
            [EnumMember(Value = "INACTIVE")]
            INACTIVE = 1
        }

        /// <summary>
        /// Status of the saved instrument. This would be &#x60;INACTIVE&#x60; when the instrument is successfully deleted.
        /// </summary>
        /// <value>Status of the saved instrument. This would be &#x60;INACTIVE&#x60; when the instrument is successfully deleted.</value>
        [DataMember(Name = "instrument_status", EmitDefaultValue = false)]
        public InstrumentStatusEnum? instrument_status { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="DeletedInstrumentEntity" /> class.
        /// </summary>
        /// <param name="customerId">Customer ID against which the card is saved..</param>
        /// <param name="afaReference">cf_payment_id of the successful transaction done while saving instrument..</param>
        /// <param name="instrumentId">Identifier for the card saved at Cashfree, which was requested to be deleted..</param>
        /// <param name="instrumentType">Type of the saved instrument..</param>
        /// <param name="instrumentUid">Unique identifier for the saved card, used to identify a specific card..</param>
        /// <param name="instrumentDisplay">Last four digits of actual card number..</param>
        /// <param name="instrumentStatus">Status of the saved instrument. This would be &#x60;INACTIVE&#x60; when the instrument is successfully deleted..</param>
        /// <param name="createdAt">Timestamp at which instrument was saved..</param>
        /// <param name="instrumentMeta">instrumentMeta.</param>
        public DeletedInstrumentEntity(string? customerId = default(string?), string? afaReference = default(string?), string? instrumentId = default(string?), InstrumentTypeEnum? instrumentType = default(InstrumentTypeEnum?), string? instrumentUid = default(string?), string? instrumentDisplay = default(string?), InstrumentStatusEnum? instrumentStatus = default(InstrumentStatusEnum?), string? createdAt = default(string?), SavedInstrumentMeta? instrumentMeta = default(SavedInstrumentMeta?))
        {
            this.customer_id = customerId;
            this.afa_reference = afaReference;
            this.instrument_id = instrumentId;
            this.instrument_type = instrumentType;
            this.instrument_uid = instrumentUid;
            this.instrument_display = instrumentDisplay;
            this.instrument_status = instrumentStatus;
            this.created_at = createdAt;
            this.instrument_meta = instrumentMeta;
        }

        /// <summary>
        /// Customer ID against which the card is saved.
        /// </summary>
        /// <value>Customer ID against which the card is saved.</value>
        [DataMember(Name = "customer_id", EmitDefaultValue = false)]
        public string? customer_id { get; set; }

        /// <summary>
        /// cf_payment_id of the successful transaction done while saving instrument.
        /// </summary>
        /// <value>cf_payment_id of the successful transaction done while saving instrument.</value>
        [DataMember(Name = "afa_reference", EmitDefaultValue = false)]
        public string? afa_reference { get; set; }

        /// <summary>
        /// Identifier for the card saved at Cashfree, which was requested to be deleted.
        /// </summary>
        /// <value>Identifier for the card saved at Cashfree, which was requested to be deleted.</value>
        [DataMember(Name = "instrument_id", EmitDefaultValue = false)]
        public string? instrument_id { get; set; }

        /// <summary>
        /// Unique identifier for the saved card, used to identify a specific card.
        /// </summary>
        /// <value>Unique identifier for the saved card, used to identify a specific card.</value>
        [DataMember(Name = "instrument_uid", EmitDefaultValue = false)]
        public string? instrument_uid { get; set; }

        /// <summary>
        /// Last four digits of actual card number.
        /// </summary>
        /// <value>Last four digits of actual card number.</value>
        [DataMember(Name = "instrument_display", EmitDefaultValue = false)]
        public string? instrument_display { get; set; }

        /// <summary>
        /// Timestamp at which instrument was saved.
        /// </summary>
        /// <value>Timestamp at which instrument was saved.</value>
        [DataMember(Name = "created_at", EmitDefaultValue = false)]
        public string? created_at { get; set; }

        /// <summary>
        /// Gets or Sets instrument_meta
        /// </summary>
        [DataMember(Name = "instrument_meta", EmitDefaultValue = false)]
        public SavedInstrumentMeta? instrument_meta { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class DeletedInstrumentEntity {\n");
            sb.Append("  customer_id: ").Append(customer_id).Append("\n");
            sb.Append("  afa_reference: ").Append(afa_reference).Append("\n");
            sb.Append("  instrument_id: ").Append(instrument_id).Append("\n");
            sb.Append("  instrument_type: ").Append(instrument_type).Append("\n");
            sb.Append("  instrument_uid: ").Append(instrument_uid).Append("\n");
            sb.Append("  instrument_display: ").Append(instrument_display).Append("\n");
            sb.Append("  instrument_status: ").Append(instrument_status).Append("\n");
            sb.Append("  created_at: ").Append(created_at).Append("\n");
            sb.Append("  instrument_meta: ").Append(instrument_meta).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        public static Boolean checkPresenceOfKey(string jsonString) {
            dynamic deserializedJsonString = JsonConvert.DeserializeObject<dynamic>(jsonString);
            if (deserializedJsonString.ContainsKey("customer_id")) {
                return true;
            }
            return false;
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }    }

}
