/*
 * Cashfree Payment Gateway APIs
 *
 * Cashfree's Payment Gateway APIs provide developers with a streamlined pathway to integrate advanced payment processing capabilities into their applications, platforms and websites.
 *
 * The version of the OpenAPI document: 2026-01-01
 * Contact: developers@cashfree.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = cashfree_pg.Client.OpenAPIDateConverter;

namespace cashfree_pg.Model
{
    /// <summary>
    /// Request body to demap soundbox vpa.
    /// </summary>
    [DataContract(Name = "DemapSoundboxVpaRequest")]
    public class DemapSoundboxVpaRequest : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="DemapSoundboxVpaRequest" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected DemapSoundboxVpaRequest() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="DemapSoundboxVpaRequest" /> class.
        /// </summary>
        /// <param name="">Cashfree terminal ID. (required).</param>
        /// <param name="">Device Serial No of soundbox that need to demap..</param>
        public DemapSoundboxVpaRequest(long  = default(long), string?  = default(string?))
        {
            this.cf_terminal_id = ;
            this.device_serial_no = ;
        }

        /// <summary>
        /// Cashfree terminal ID.
        /// </summary>
        /// <value>Cashfree terminal ID.</value>
        [DataMember(Name = "cf_terminal_id", IsRequired = true, EmitDefaultValue = true)]
        public long cf_terminal_id { get; set; }

        /// <summary>
        /// Device Serial No of soundbox that need to demap.
        /// </summary>
        /// <value>Device Serial No of soundbox that need to demap.</value>
        [DataMember(Name = "device_serial_no", EmitDefaultValue = false)]
        public string? device_serial_no { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class DemapSoundboxVpaRequest {\n");
            sb.Append("  cf_terminal_id: ").Append(cf_terminal_id).Append("\n");
            sb.Append("  device_serial_no: ").Append(device_serial_no).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }    }

}
