/*
 * Cashfree Payment Gateway APIs
 *
 * Cashfree's Payment Gateway APIs provide developers with a streamlined pathway to integrate advanced payment processing capabilities into their applications, platforms and websites.
 *
 * The version of the OpenAPI document: 2023-08-01
 * Contact: developers@cashfree.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = cashfree_pg.Client.OpenAPIDateConverter;

namespace cashfree_pg.Model
{
    /// <summary>
    /// EligibilityMethodItemEntityDetailsAvailableHandlesInner
    /// </summary>
    [DataContract(Name = "EligibilityMethodItem_entity_details_available_handles_inner")]
    public class EligibilityMethodItemEntityDetailsAvailableHandlesInner : IEquatable<EligibilityMethodItemEntityDetailsAvailableHandlesInner>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="EligibilityMethodItemEntityDetailsAvailableHandlesInner" /> class.
        /// </summary>
        /// <param name="handle">VPA handle.</param>
        /// <param name="application">Application or service related to the VPA handle..</param>
        public EligibilityMethodItemEntityDetailsAvailableHandlesInner(string? handle = default(string?), string? application = default(string?))
        {
            this.handle = handle;
            this.application = application;
        }

        /// <summary>
        /// VPA handle
        /// </summary>
        /// <value>VPA handle</value>
        [DataMember(Name = "handle", EmitDefaultValue = false)]
        public string? handle { get; set; }

        /// <summary>
        /// Application or service related to the VPA handle.
        /// </summary>
        /// <value>Application or service related to the VPA handle.</value>
        [DataMember(Name = "application", EmitDefaultValue = false)]
        public string? application { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class EligibilityMethodItemEntityDetailsAvailableHandlesInner {\n");
            sb.Append("  handle: ").Append(handle).Append("\n");
            sb.Append("  application: ").Append(application).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as EligibilityMethodItemEntityDetailsAvailableHandlesInner);
        }

        /// <summary>
        /// Returns true if EligibilityMethodItemEntityDetailsAvailableHandlesInner instances are equal
        /// </summary>
        /// <param name="input">Instance of EligibilityMethodItemEntityDetailsAvailableHandlesInner to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(EligibilityMethodItemEntityDetailsAvailableHandlesInner input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.handle == input.handle ||
                    (this.handle != null &&
                    this.handle.Equals(input.handle))
                ) && 
                (
                    this.application == input.application ||
                    (this.application != null &&
                    this.application.Equals(input.application))
                );
        }

        public static Boolean checkPresenceOfKey(string jsonStringhandle) {
            dynamic deserializedJsonString = JsonConvert.DeserializeObject<dynamic>(jsonStringhandle);
            if (deserializedJsonString.ContainsKey("handle")) {
                return true;
            }
            return false;
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.handle != null)
                {
                    hashCode = (hashCode * 59) + this.handle.GetHashCode();
                }
                if (this.application != null)
                {
                    hashCode = (hashCode * 59) + this.application.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
