/*
 * Cashfree Payment Gateway APIs
 *
 * Cashfree's Payment Gateway APIs provide developers with a streamlined pathway to integrate advanced payment processing capabilities into their applications, platforms and websites.
 *
 * The version of the OpenAPI document: 2023-08-01
 * Contact: developers@cashfree.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = cashfree_pg.Client.OpenAPIDateConverter;

namespace cashfree_pg.Model
{
    /// <summary>
    /// Entity Simulation it contains payment_status and payment_error_code
    /// </summary>
    [DataContract(Name = "EntitySimulationResponse")]
    public class EntitySimulationResponse : IEquatable<EntitySimulationResponse>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="EntitySimulationResponse" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected EntitySimulationResponse() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="EntitySimulationResponse" /> class.
        /// </summary>
        /// <param name="paymentStatus">Payment Status (required).</param>
        /// <param name="paymentErrorCode">Payment Error Code.</param>
        public EntitySimulationResponse(string paymentStatus = default(string), string? paymentErrorCode = default(string?))
        {
            // to ensure "paymentStatus" is required (not null)
            if (paymentStatus == null)
            {
                throw new ArgumentNullException("paymentStatus is a required property for EntitySimulationResponse and cannot be null");
            }
            this.payment_status = paymentStatus;
            this.payment_error_code = paymentErrorCode;
        }

        /// <summary>
        /// Payment Status
        /// </summary>
        /// <value>Payment Status</value>
        [DataMember(Name = "payment_status", IsRequired = true, EmitDefaultValue = true)]
        public string payment_status { get; set; }

        /// <summary>
        /// Payment Error Code
        /// </summary>
        /// <value>Payment Error Code</value>
        [DataMember(Name = "payment_error_code", EmitDefaultValue = false)]
        public string? payment_error_code { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class EntitySimulationResponse {\n");
            sb.Append("  payment_status: ").Append(payment_status).Append("\n");
            sb.Append("  payment_error_code: ").Append(payment_error_code).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as EntitySimulationResponse);
        }

        /// <summary>
        /// Returns true if EntitySimulationResponse instances are equal
        /// </summary>
        /// <param name="input">Instance of EntitySimulationResponse to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(EntitySimulationResponse input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.payment_status == input.payment_status ||
                    (this.payment_status != null &&
                    this.payment_status.Equals(input.payment_status))
                ) && 
                (
                    this.payment_error_code == input.payment_error_code ||
                    (this.payment_error_code != null &&
                    this.payment_error_code.Equals(input.payment_error_code))
                );
        }

        public static Boolean checkPresenceOfKey(string jsonStringpayment_status) {
            dynamic deserializedJsonString = JsonConvert.DeserializeObject<dynamic>(jsonStringpayment_status);
            if (deserializedJsonString.ContainsKey("payment_status")) {
                return true;
            }
            return false;
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.payment_status != null)
                {
                    hashCode = (hashCode * 59) + this.payment_status.GetHashCode();
                }
                if (this.payment_error_code != null)
                {
                    hashCode = (hashCode * 59) + this.payment_error_code.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
