/*
 * Cashfree Payment Gateway APIs
 *
 * Cashfree's Payment Gateway APIs provide developers with a streamlined pathway to integrate advanced payment processing capabilities into their applications, platforms and websites.
 *
 * The version of the OpenAPI document: 2025-01-01
 * Contact: developers@cashfree.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = cashfree_pg.Client.OpenAPIDateConverter;

namespace cashfree_pg.Model
{
    /// <summary>
    /// Use this to set configurations for the products like One Click Checkout, Verify and Pay, if they are enabled for your account
    /// </summary>
    [DataContract(Name = "products")]
    public class Products : IEquatable<Products>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Products" /> class.
        /// </summary>
        /// <param name="oneClickCheckout">oneClickCheckout.</param>
        /// <param name="verifyPay">verifyPay.</param>
        public Products(ProductDetails? oneClickCheckout = default(ProductDetails?), ProductDetails? verifyPay = default(ProductDetails?))
        {
            this.one_click_checkout = oneClickCheckout;
            this.verify_pay = verifyPay;
        }

        /// <summary>
        /// Gets or Sets one_click_checkout
        /// </summary>
        [DataMember(Name = "one_click_checkout", EmitDefaultValue = false)]
        public ProductDetails? one_click_checkout { get; set; }

        /// <summary>
        /// Gets or Sets verify_pay
        /// </summary>
        [DataMember(Name = "verify_pay", EmitDefaultValue = false)]
        public ProductDetails? verify_pay { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class Products {\n");
            sb.Append("  one_click_checkout: ").Append(one_click_checkout).Append("\n");
            sb.Append("  verify_pay: ").Append(verify_pay).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as Products);
        }

        /// <summary>
        /// Returns true if Products instances are equal
        /// </summary>
        /// <param name="input">Instance of Products to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(Products input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.one_click_checkout == input.one_click_checkout ||
                    (this.one_click_checkout != null &&
                    this.one_click_checkout.Equals(input.one_click_checkout))
                ) && 
                (
                    this.verify_pay == input.verify_pay ||
                    (this.verify_pay != null &&
                    this.verify_pay.Equals(input.verify_pay))
                );
        }

        public static Boolean checkPresenceOfKey(string jsonStringone_click_checkout) {
            dynamic deserializedJsonString = JsonConvert.DeserializeObject<dynamic>(jsonStringone_click_checkout);
            if (deserializedJsonString.ContainsKey("one_click_checkout")) {
                return true;
            }
            return false;
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.one_click_checkout != null)
                {
                    hashCode = (hashCode * 59) + this.one_click_checkout.GetHashCode();
                }
                if (this.verify_pay != null)
                {
                    hashCode = (hashCode * 59) + this.verify_pay.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
