/*
 * Cashfree Payment Gateway APIs
 *
 * Cashfree's Payment Gateway APIs provide developers with a streamlined pathway to integrate advanced payment processing capabilities into their applications, platforms and websites.
 *
 * The version of the OpenAPI document: 2023-08-01
 * Contact: developers@cashfree.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = cashfree_pg.Client.OpenAPIDateConverter;

namespace cashfree_pg.Model
{
    /// <summary>
    /// StaticSplitRequestSchemeInner
    /// </summary>
    [DataContract(Name = "StaticSplitRequest_scheme_inner")]
    public class StaticSplitRequestSchemeInner : IEquatable<StaticSplitRequestSchemeInner>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="StaticSplitRequestSchemeInner" /> class.
        /// </summary>
        /// <param name="merchantVendorId">Specify the merchant vendor ID to create the split scheme for the payment..</param>
        /// <param name="percentage">Specify the percentage of amount to be split..</param>
        public StaticSplitRequestSchemeInner(string? merchantVendorId = default(string?), string? percentage = default(string?))
        {
            this.merchantVendorId = merchantVendorId;
            this.percentage = percentage;
        }

        /// <summary>
        /// Specify the merchant vendor ID to create the split scheme for the payment.
        /// </summary>
        /// <value>Specify the merchant vendor ID to create the split scheme for the payment.</value>
        [DataMember(Name = "merchantVendorId", EmitDefaultValue = false)]
        public string? merchantVendorId { get; set; }

        /// <summary>
        /// Specify the percentage of amount to be split.
        /// </summary>
        /// <value>Specify the percentage of amount to be split.</value>
        [DataMember(Name = "percentage", EmitDefaultValue = false)]
        public string? percentage { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class StaticSplitRequestSchemeInner {\n");
            sb.Append("  merchantVendorId: ").Append(merchantVendorId).Append("\n");
            sb.Append("  percentage: ").Append(percentage).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as StaticSplitRequestSchemeInner);
        }

        /// <summary>
        /// Returns true if StaticSplitRequestSchemeInner instances are equal
        /// </summary>
        /// <param name="input">Instance of StaticSplitRequestSchemeInner to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(StaticSplitRequestSchemeInner input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.merchantVendorId == input.merchantVendorId ||
                    (this.merchantVendorId != null &&
                    this.merchantVendorId.Equals(input.merchantVendorId))
                ) && 
                (
                    this.percentage == input.percentage ||
                    (this.percentage != null &&
                    this.percentage.Equals(input.percentage))
                );
        }

        public static Boolean checkPresenceOfKey(string jsonStringmerchantVendorId) {
            dynamic deserializedJsonString = JsonConvert.DeserializeObject<dynamic>(jsonStringmerchantVendorId);
            if (deserializedJsonString.ContainsKey("merchantVendorId")) {
                return true;
            }
            return false;
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.merchantVendorId != null)
                {
                    hashCode = (hashCode * 59) + this.merchantVendorId.GetHashCode();
                }
                if (this.percentage != null)
                {
                    hashCode = (hashCode * 59) + this.percentage.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
