/*
 * Cashfree Payment Gateway APIs
 *
 * Cashfree's Payment Gateway APIs provide developers with a streamlined pathway to integrate advanced payment processing capabilities into their applications, platforms and websites.
 *
 * The version of the OpenAPI document: 2026-01-01
 * Contact: developers@cashfree.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = cashfree_pg.Client.OpenAPIDateConverter;

namespace cashfree_pg.Model
{
    /// <summary>
    /// TransferDetailsTagsInner
    /// </summary>
    [DataContract(Name = "TransferDetails_tags_inner")]
    public class TransferDetailsTagsInner : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="TransferDetailsTagsInner" /> class.
        /// </summary>
        /// <param name="product">product.</param>
        /// <param name="size">size.</param>
        public TransferDetailsTagsInner(string? product = default(string?), decimal? size = default(decimal?))
        {
            this.product = product;
            this.size = size;
        }

        /// <summary>
        /// Gets or Sets product
        /// </summary>
        [DataMember(Name = "product", EmitDefaultValue = false)]
        public string? product { get; set; }

        /// <summary>
        /// Gets or Sets size
        /// </summary>
        [DataMember(Name = "size", EmitDefaultValue = false)]
        public decimal? size { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class TransferDetailsTagsInner {\n");
            sb.Append("  product: ").Append(product).Append("\n");
            sb.Append("  size: ").Append(size).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }    }

}
