/*
 * Cashfree Payment Gateway APIs
 *
 * Cashfree's Payment Gateway APIs provide developers with a streamlined pathway to integrate advanced payment processing capabilities into their applications, platforms and websites.
 *
 * The version of the OpenAPI document: 2026-01-01
 * Contact: developers@cashfree.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = cashfree_pg.Client.OpenAPIDateConverter;

namespace cashfree_pg.Model
{
    /// <summary>
    /// UPIDowntimeUpi
    /// </summary>
    [DataContract(Name = "UPIDowntime_upi")]
    public class UPIDowntimeUpi : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="UPIDowntimeUpi" /> class.
        /// </summary>
        /// <param name="upiIssuer">upiIssuer.</param>
        /// <param name="upiPsp">upiPsp.</param>
        /// <param name="upiVpa">upiVpa.</param>
        /// <param name="isNpciDowntime">isNpciDowntime.</param>
        public UPIDowntimeUpi(List<string>? upiIssuer = default(List<string>?), List<string>? upiPsp = default(List<string>?), List<string>? upiVpa = default(List<string>?), bool? isNpciDowntime = default(bool?))
        {
            this.upi_issuer = upiIssuer;
            this.upi_psp = upiPsp;
            this.upi_vpa = upiVpa;
            this.is_npci_downtime = isNpciDowntime;
        }

        /// <summary>
        /// Gets or Sets upi_issuer
        /// </summary>
        /// <example>[&quot;ALL_BANKS&quot;]</example>
        [DataMember(Name = "upi_issuer", EmitDefaultValue = false)]
        public List<string>? upi_issuer { get; set; }

        /// <summary>
        /// Gets or Sets upi_psp
        /// </summary>
        /// <example>[&quot;ALL_PSP&quot;]</example>
        [DataMember(Name = "upi_psp", EmitDefaultValue = false)]
        public List<string>? upi_psp { get; set; }

        /// <summary>
        /// Gets or Sets upi_vpa
        /// </summary>
        /// <example>[&quot;ybl&quot;]</example>
        [DataMember(Name = "upi_vpa", EmitDefaultValue = false)]
        public List<string>? upi_vpa { get; set; }

        /// <summary>
        /// Gets or Sets is_npci_downtime
        /// </summary>
        /// <example>false</example>
        [DataMember(Name = "is_npci_downtime", EmitDefaultValue = true)]
        public bool? is_npci_downtime { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class UPIDowntimeUpi {\n");
            sb.Append("  upi_issuer: ").Append(upi_issuer).Append("\n");
            sb.Append("  upi_psp: ").Append(upi_psp).Append("\n");
            sb.Append("  upi_vpa: ").Append(upi_vpa).Append("\n");
            sb.Append("  is_npci_downtime: ").Append(is_npci_downtime).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }    }

}
