/*
 * Cashfree Payment Gateway APIs
 *
 * Cashfree's Payment Gateway APIs provide developers with a streamlined pathway to integrate advanced payment processing capabilities into their applications, platforms and websites.
 *
 * The version of the OpenAPI document: 2026-01-01
 * Contact: developers@cashfree.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = cashfree_pg.Client.OpenAPIDateConverter;

namespace cashfree_pg.Model
{
    /// <summary>
    /// Vendor Adjustment Request Body.
    /// </summary>
    [DataContract(Name = "VendorAdjustmentRequest")]
    public class VendorAdjustmentRequest : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="VendorAdjustmentRequest" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected VendorAdjustmentRequest() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="VendorAdjustmentRequest" /> class.
        /// </summary>
        /// <param name="">The unique identifier of the vendor to whom the adjustment is applied. (required).</param>
        /// <param name="">The unique identifier for the adjustment transaction. (required).</param>
        /// <param name="">The adjustment amount to be applied. (required).</param>
        /// <param name="">The type of adjustment. Possible values: CREDIT, DEBIT. (required).</param>
        /// <param name="">Remarks for the adjustment transaction, if any..</param>
        public VendorAdjustmentRequest(string  = default(string), long  = default(long), decimal  = default(decimal), string  = default(string), string?  = default(string?))
        {
            // to ensure "" is required (not null)
            if ( == null)
            {
                throw new ArgumentNullException(" is a required property for VendorAdjustmentRequest and cannot be null");
            }
            this.vendor_id = ;
            this.adjustment_id = ;
            this.amount = ;
            // to ensure "" is required (not null)
            if ( == null)
            {
                throw new ArgumentNullException(" is a required property for VendorAdjustmentRequest and cannot be null");
            }
            this.type = ;
            this.remarks = ;
        }

        /// <summary>
        /// The unique identifier of the vendor to whom the adjustment is applied.
        /// </summary>
        /// <value>The unique identifier of the vendor to whom the adjustment is applied.</value>
        [DataMember(Name = "vendor_id", IsRequired = true, EmitDefaultValue = true)]
        public string vendor_id { get; set; }

        /// <summary>
        /// The unique identifier for the adjustment transaction.
        /// </summary>
        /// <value>The unique identifier for the adjustment transaction.</value>
        [DataMember(Name = "adjustment_id", IsRequired = true, EmitDefaultValue = true)]
        public long adjustment_id { get; set; }

        /// <summary>
        /// The adjustment amount to be applied.
        /// </summary>
        /// <value>The adjustment amount to be applied.</value>
        [DataMember(Name = "amount", IsRequired = true, EmitDefaultValue = true)]
        public decimal amount { get; set; }

        /// <summary>
        /// The type of adjustment. Possible values: CREDIT, DEBIT.
        /// </summary>
        /// <value>The type of adjustment. Possible values: CREDIT, DEBIT.</value>
        [DataMember(Name = "type", IsRequired = true, EmitDefaultValue = true)]
        public string type { get; set; }

        /// <summary>
        /// Remarks for the adjustment transaction, if any.
        /// </summary>
        /// <value>Remarks for the adjustment transaction, if any.</value>
        [DataMember(Name = "remarks", EmitDefaultValue = false)]
        public string? remarks { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class VendorAdjustmentRequest {\n");
            sb.Append("  vendor_id: ").Append(vendor_id).Append("\n");
            sb.Append("  adjustment_id: ").Append(adjustment_id).Append("\n");
            sb.Append("  amount: ").Append(amount).Append("\n");
            sb.Append("  type: ").Append(type).Append("\n");
            sb.Append("  remarks: ").Append(remarks).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }    }

}
