/*
 * Cashfree Payment Gateway APIs
 *
 * Cashfree's Payment Gateway APIs provide developers with a streamlined pathway to integrate advanced payment processing capabilities into their applications, platforms and websites.
 *
 * The version of the OpenAPI document: 2026-01-01
 * Contact: developers@cashfree.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = cashfree-dotnet-pg-sdk.Client.OpenAPIDateConverter;

namespace cashfree-dotnet-pg-sdk.Model
{
    /// <summary>
    /// Error when resource requested is not found.
    /// </summary>
    [DataContract(Name = "ApiError404")]
    public class ApiError404 : IValidatableObject
    {
        /// <summary>
        /// invalid_request_error.
        /// </summary>
        /// <value>invalid_request_error.</value>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum TypeEnum
        {
            /// <summary>
            /// Enum InvalidRequestError for value: invalid_request_error
            /// </summary>
            [EnumMember(Value = "invalid_request_error")]
            InvalidRequestError = 1
        }

        /// <summary>
        /// invalid_request_error.
        /// </summary>
        /// <value>invalid_request_error.</value>
        [DataMember(Name = "type", EmitDefaultValue = false)]
        public TypeEnum? type { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="ApiError404" /> class.
        /// </summary>
        /// <param name="">.</param>
        /// <param name="">.</param>
        /// <param name="">.</param>
        /// <param name="">invalid_request_error..</param>
        public ApiError404(string?  = default(string?), string?  = default(string?), string?  = default(string?), TypeEnum?  = default(TypeEnum?))
        {
            this.message = ;
            this.code = ;
            this.help = ;
            this.type = ;
        }

        /// <summary>
        /// Gets or Sets message
        /// </summary>
        [DataMember(Name = "message", EmitDefaultValue = false)]
        public string? message { get; set; }

        /// <summary>
        /// Gets or Sets code
        /// </summary>
        [DataMember(Name = "code", EmitDefaultValue = false)]
        public string? code { get; set; }

        /// <summary>
        /// Gets or Sets help
        /// </summary>
        [DataMember(Name = "help", EmitDefaultValue = false)]
        public string? help { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ApiError404 {\n");
            sb.Append("  message: ").Append(message).Append("\n");
            sb.Append("  code: ").Append(code).Append("\n");
            sb.Append("  help: ").Append(help).Append("\n");
            sb.Append("  type: ").Append(type).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }    }

}
