/* tslint:disable */
/* eslint-disable */
/**
 * Cashfree Payment Gateway APIs
 * Cashfree's Payment Gateway APIs provide developers with a streamlined pathway to integrate advanced payment processing capabilities into their applications, platforms and websites.
 *
 * The version of the OpenAPI document: 2026-01-01
 * Contact: developers@cashfree.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * duplicate request.
 * @export
 * @interface ApiError409
 */
export interface ApiError409 {
    /**
     * 
     * @type {string}
     * @memberof ApiError409
     */
    'message'?: string;
    /**
     * 
     * @type {string}
     * @memberof ApiError409
     */
    'help'?: string;
    /**
     * 
     * @type {string}
     * @memberof ApiError409
     */
    'code'?: string;
    /**
     * invalid_request_error.
     * @type {string}
     * @memberof ApiError409
     */
    'type'?: TypeEnum;
}

export const TypeEnum = {
    InvalidRequestError: invalid_request_error,
    UnknownDefaultOpenApi: unknown_default_open_api
} as const;

export type TypeEnum = typeof TypeEnum[keyof typeof TypeEnum];

