/* tslint:disable */
/* eslint-disable */
/**
 * Cashfree Payment Gateway APIs
 * Cashfree's Payment Gateway APIs provide developers with a streamlined pathway to integrate advanced payment processing capabilities into their applications, platforms and websites.
 *
 * The version of the OpenAPI document: 2026-01-01
 * Contact: developers@cashfree.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Payment method upi.
 * @export
 * @interface AuthResponseUpi
 */
export interface AuthResponseUpi {
    /**
     * Can be link, qrcode, or collect.
     * @type {string}
     * @memberof AuthResponseUpi
     */
    'channel'?: string;
    /**
     * Virtual payment address (UPI ID) of the user.
     * @type {string}
     * @memberof AuthResponseUpi
     */
    'upi_id'?: string;
    /**
     * UPI instrument used for payment.
     * @type {string}
     * @memberof AuthResponseUpi
     */
    'upi_instrument'?: string;
    /**
     * Unique number representing the UPI instrument.
     * @type {string}
     * @memberof AuthResponseUpi
     */
    'upi_instrument_number'?: string;
    /**
     * Account number of the UPI payer.
     * @type {string}
     * @memberof AuthResponseUpi
     */
    'upi_payer_account_number'?: string;
    /**
     * IFSC code of the UPI payer's bank.
     * @type {string}
     * @memberof AuthResponseUpi
     */
    'upi_payer_ifsc'?: string;
}
