/* tslint:disable */
/* eslint-disable */
/**
 * Cashfree Payment Gateway APIs
 * Cashfree's Payment Gateway APIs provide developers with a streamlined pathway to integrate advanced payment processing capabilities into their applications, platforms and websites.
 *
 * The version of the OpenAPI document: 2026-01-01
 * Contact: developers@cashfree.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Payment method pnach.
 * @export
 * @interface AuthResponsePnach
 */
export interface AuthResponsePnach {
    /**
     * Channel. Can be post.
     * @type {string}
     * @memberof AuthResponsePnach
     */
    'channel'?: string;
    /**
     * Date on which the mandate was created. Cashfree stores timestamps in IST.
     * @type {string}
     * @memberof AuthResponsePnach
     */
    'mandate_creation_date'?: string;
    /**
     * Start date of the mandate. Cashfree stores timestamps in IST.
     * @type {string}
     * @memberof AuthResponsePnach
     */
    'mandate_start_date'?: string;
    /**
     * Type of the bank account.
     * @type {string}
     * @memberof AuthResponsePnach
     */
    'account_type'?: string;
    /**
     * Bank account number.
     * @type {string}
     * @memberof AuthResponsePnach
     */
    'account_number'?: string;
    /**
     * IFSC code of the bank account.
     * @type {string}
     * @memberof AuthResponsePnach
     */
    'account_ifsc'?: string;
    /**
     * Name of the account holder.
     * @type {string}
     * @memberof AuthResponsePnach
     */
    'account_holder_name'?: string;
    /**
     * Bank code of the account-holding bank.
     * @type {string}
     * @memberof AuthResponsePnach
     */
    'account_bank_code'?: string;
}
