/*
 * Cashfree Payment Gateway APIs
 *
 * Cashfree's Payment Gateway APIs provide developers with a streamlined pathway to integrate advanced payment processing capabilities into their applications, platforms and websites.
 *
 * The version of the OpenAPI document: 2026-01-01
 * Contact: developers@cashfree.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = cashfree-dotnet-pg-sdk.Client.OpenAPIDateConverter;

namespace cashfree-dotnet-pg-sdk.Model
{
    /// <summary>
    /// CardOffer
    /// </summary>
    [DataContract(Name = "Card_Offer")]
    public class CardOffer : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CardOffer" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected CardOffer() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="CardOffer" /> class.
        /// </summary>
        /// <param name=""> (required).</param>
        /// <param name="">Bank Name of Card. (required).</param>
        /// <param name=""> (required).</param>
        public CardOffer(List<string>  = default(List<string>), string  = default(string), List<string>  = default(List<string>))
        {
            // to ensure "" is required (not null)
            if ( == null)
            {
                throw new ArgumentNullException(" is a required property for CardOffer and cannot be null");
            }
            this.type = ;
            // to ensure "" is required (not null)
            if ( == null)
            {
                throw new ArgumentNullException(" is a required property for CardOffer and cannot be null");
            }
            this.bank_name = ;
            // to ensure "" is required (not null)
            if ( == null)
            {
                throw new ArgumentNullException(" is a required property for CardOffer and cannot be null");
            }
            this.scheme_name = ;
        }

        /// <summary>
        /// Gets or Sets type
        /// </summary>
        [DataMember(Name = "type", IsRequired = true, EmitDefaultValue = true)]
        public List<string> type { get; set; }

        /// <summary>
        /// Bank Name of Card.
        /// </summary>
        /// <value>Bank Name of Card.</value>
        /// <example>hdfc bank</example>
        [DataMember(Name = "bank_name", IsRequired = true, EmitDefaultValue = true)]
        public string bank_name { get; set; }

        /// <summary>
        /// Gets or Sets scheme_name
        /// </summary>
        [DataMember(Name = "scheme_name", IsRequired = true, EmitDefaultValue = true)]
        public List<string> scheme_name { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class CardOffer {\n");
            sb.Append("  type: ").Append(type).Append("\n");
            sb.Append("  bank_name: ").Append(bank_name).Append("\n");
            sb.Append("  scheme_name: ").Append(scheme_name).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // bank_name (string) maxLength
            if (this.bank_name != null && this.bank_name.Length > 100)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for bank_name, length must be less than 100.", new [] { "bank_name" });
            }

            // bank_name (string) minLength
            if (this.bank_name != null && this.bank_name.Length < 3)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for bank_name, length must be greater than 3.", new [] { "bank_name" });
            }

            yield break;
        }    }

}
