/*
 * Cashfree Payment Gateway APIs
 *
 * Cashfree's Payment Gateway APIs provide developers with a streamlined pathway to integrate advanced payment processing capabilities into their applications, platforms and websites.
 *
 * The version of the OpenAPI document: 2026-01-01
 * Contact: developers@cashfree.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = cashfree-dotnet-pg-sdk.Client.OpenAPIDateConverter;

namespace cashfree-dotnet-pg-sdk.Model
{
    /// <summary>
    /// CreateSubscriptionRequestPlanDetails
    /// </summary>
    [DataContract(Name = "CreateSubscriptionRequest_plan_details")]
    public class CreateSubscriptionRequestPlanDetails : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CreateSubscriptionRequestPlanDetails" /> class.
        /// </summary>
        /// <param name="">The unique identifier used to create plan. You only need to pass this field if you had already created plan. Otherwise use the other fields here to define the plan..</param>
        /// <param name="">Specify plan name for easy reference..</param>
        /// <param name="">Possible values ON_DEMAND or PERIODIC. PERIODIC - Payments are triggered automatically at fixed intervals defined by the merchant. ON_DEMAND - Merchant needs to trigger/charge the customer explicitly with the required amount..</param>
        /// <param name="">INR by default. For subscriptions in non-INR currency, please refer to [supported currencies](https://www.cashfree.com/docs/payments/international-payments/ipg/currencies-supported#full-currency-list)..</param>
        /// <param name="">The amount to be charged for PERIODIC plan. This is a conditional parameter, only required for PERIODIC plans..</param>
        /// <param name="">This is the maximum amount that can be charged on a subscription..</param>
        /// <param name="">Maximum number of debits set for the plan. The subscription will automatically change to COMPLETED status once this limit is reached..</param>
        /// <param name="">Number of intervals of intervalType between every subscription payment. For example, to charge a customer bi-weekly use intervalType as “week” and intervals as 2. Required for PERIODIC plan. The default value is 1..</param>
        /// <param name="">The type of interval for a PERIODIC plan like DAY, WEEK, MONTH, or YEAR. This is a conditional parameter only applicable for PERIODIC plans..</param>
        /// <param name="">Note for the plan..</param>
        public CreateSubscriptionRequestPlanDetails(string?  = default(string?), string?  = default(string?), string?  = default(string?), string?  = default(string?), decimal?  = default(decimal?), decimal?  = default(decimal?), int?  = default(int?), int?  = default(int?), string?  = default(string?), string?  = default(string?))
        {
            this.plan_id = ;
            this.plan_name = ;
            this.plan_type = ;
            this.plan_currency = ;
            this.plan_amount = ;
            this.plan_max_amount = ;
            this.plan_max_cycles = ;
            this.plan_intervals = ;
            this.plan_interval_type = ;
            this.plan_note = ;
        }

        /// <summary>
        /// The unique identifier used to create plan. You only need to pass this field if you had already created plan. Otherwise use the other fields here to define the plan.
        /// </summary>
        /// <value>The unique identifier used to create plan. You only need to pass this field if you had already created plan. Otherwise use the other fields here to define the plan.</value>
        [DataMember(Name = "plan_id", EmitDefaultValue = false)]
        public string? plan_id { get; set; }

        /// <summary>
        /// Specify plan name for easy reference.
        /// </summary>
        /// <value>Specify plan name for easy reference.</value>
        [DataMember(Name = "plan_name", EmitDefaultValue = false)]
        public string? plan_name { get; set; }

        /// <summary>
        /// Possible values ON_DEMAND or PERIODIC. PERIODIC - Payments are triggered automatically at fixed intervals defined by the merchant. ON_DEMAND - Merchant needs to trigger/charge the customer explicitly with the required amount.
        /// </summary>
        /// <value>Possible values ON_DEMAND or PERIODIC. PERIODIC - Payments are triggered automatically at fixed intervals defined by the merchant. ON_DEMAND - Merchant needs to trigger/charge the customer explicitly with the required amount.</value>
        [DataMember(Name = "plan_type", EmitDefaultValue = false)]
        public string? plan_type { get; set; }

        /// <summary>
        /// INR by default. For subscriptions in non-INR currency, please refer to [supported currencies](https://www.cashfree.com/docs/payments/international-payments/ipg/currencies-supported#full-currency-list).
        /// </summary>
        /// <value>INR by default. For subscriptions in non-INR currency, please refer to [supported currencies](https://www.cashfree.com/docs/payments/international-payments/ipg/currencies-supported#full-currency-list).</value>
        [DataMember(Name = "plan_currency", EmitDefaultValue = false)]
        public string? plan_currency { get; set; }

        /// <summary>
        /// The amount to be charged for PERIODIC plan. This is a conditional parameter, only required for PERIODIC plans.
        /// </summary>
        /// <value>The amount to be charged for PERIODIC plan. This is a conditional parameter, only required for PERIODIC plans.</value>
        [DataMember(Name = "plan_amount", EmitDefaultValue = false)]
        public decimal? plan_amount { get; set; }

        /// <summary>
        /// This is the maximum amount that can be charged on a subscription.
        /// </summary>
        /// <value>This is the maximum amount that can be charged on a subscription.</value>
        [DataMember(Name = "plan_max_amount", EmitDefaultValue = false)]
        public decimal? plan_max_amount { get; set; }

        /// <summary>
        /// Maximum number of debits set for the plan. The subscription will automatically change to COMPLETED status once this limit is reached.
        /// </summary>
        /// <value>Maximum number of debits set for the plan. The subscription will automatically change to COMPLETED status once this limit is reached.</value>
        [DataMember(Name = "plan_max_cycles", EmitDefaultValue = false)]
        public int? plan_max_cycles { get; set; }

        /// <summary>
        /// Number of intervals of intervalType between every subscription payment. For example, to charge a customer bi-weekly use intervalType as “week” and intervals as 2. Required for PERIODIC plan. The default value is 1.
        /// </summary>
        /// <value>Number of intervals of intervalType between every subscription payment. For example, to charge a customer bi-weekly use intervalType as “week” and intervals as 2. Required for PERIODIC plan. The default value is 1.</value>
        [DataMember(Name = "plan_intervals", EmitDefaultValue = false)]
        public int? plan_intervals { get; set; }

        /// <summary>
        /// The type of interval for a PERIODIC plan like DAY, WEEK, MONTH, or YEAR. This is a conditional parameter only applicable for PERIODIC plans.
        /// </summary>
        /// <value>The type of interval for a PERIODIC plan like DAY, WEEK, MONTH, or YEAR. This is a conditional parameter only applicable for PERIODIC plans.</value>
        [DataMember(Name = "plan_interval_type", EmitDefaultValue = false)]
        public string? plan_interval_type { get; set; }

        /// <summary>
        /// Note for the plan.
        /// </summary>
        /// <value>Note for the plan.</value>
        [DataMember(Name = "plan_note", EmitDefaultValue = false)]
        public string? plan_note { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class CreateSubscriptionRequestPlanDetails {\n");
            sb.Append("  plan_id: ").Append(plan_id).Append("\n");
            sb.Append("  plan_name: ").Append(plan_name).Append("\n");
            sb.Append("  plan_type: ").Append(plan_type).Append("\n");
            sb.Append("  plan_currency: ").Append(plan_currency).Append("\n");
            sb.Append("  plan_amount: ").Append(plan_amount).Append("\n");
            sb.Append("  plan_max_amount: ").Append(plan_max_amount).Append("\n");
            sb.Append("  plan_max_cycles: ").Append(plan_max_cycles).Append("\n");
            sb.Append("  plan_intervals: ").Append(plan_intervals).Append("\n");
            sb.Append("  plan_interval_type: ").Append(plan_interval_type).Append("\n");
            sb.Append("  plan_note: ").Append(plan_note).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // plan_name (string) maxLength
            if (this.plan_name != null && this.plan_name.Length > 40)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for plan_name, length must be less than 40.", new [] { "plan_name" });
            }

            yield break;
        }    }

}
