/* tslint:disable */
/* eslint-disable */
/**
 * Cashfree Payment Gateway APIs
 * Cashfree's Payment Gateway APIs provide developers with a streamlined pathway to integrate advanced payment processing capabilities into their applications, platforms and websites.
 *
 * The version of the OpenAPI document: 2026-01-01
 * Contact: developers@cashfree.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Payment link customer entity.
 * @export
 * @interface LinkCustomerDetailsEntity
 */
export interface LinkCustomerDetailsEntity {
    /**
     * Customer phone number.
     * @type {string}
     * @memberof LinkCustomerDetailsEntity
     */
    'customer_phone': string;
    /**
     * Customer email address.
     * @type {string}
     * @memberof LinkCustomerDetailsEntity
     */
    'customer_email'?: string;
    /**
     * Customer name.
     * @type {string}
     * @memberof LinkCustomerDetailsEntity
     */
    'customer_name'?: string;
    /**
     * Customer Bank Account Number.
     * @type {string}
     * @memberof LinkCustomerDetailsEntity
     */
    'customer_bank_account_number'?: string;
    /**
     * Customer Bank Ifsc.
     * @type {string}
     * @memberof LinkCustomerDetailsEntity
     */
    'customer_bank_ifsc'?: string;
    /**
     * Customer Bank Code.
     * @type {int}
     * @memberof LinkCustomerDetailsEntity
     */
    'customer_bank_code'?: CustomerBankCodeEnum;
    /**
     * Customer Bank Account Holder Name.
     * @type {string}
     * @memberof LinkCustomerDetailsEntity
     */
    'customer_bank_acoount_holder_name'?: string;
}

export const CustomerBankCodeEnum = {
    NUMBER_3003: 3003,
    NUMBER_3005: 3005,
    NUMBER_3006: 3006,
    NUMBER_3010: 3010,
    NUMBER_3012: 3012,
    NUMBER_3016: 3016,
    NUMBER_3019: 3019,
    NUMBER_3020: 3020,
    NUMBER_3021: 3021,
    NUMBER_3022: 3022,
    NUMBER_3023: 3023,
    NUMBER_3024: 3024,
    NUMBER_3026: 3026,
    NUMBER_3027: 3027,
    NUMBER_3028: 3028,
    NUMBER_3029: 3029,
    NUMBER_3030: 3030,
    NUMBER_3031: 3031,
    NUMBER_3032: 3032,
    NUMBER_3033: 3033,
    NUMBER_3038: 3038,
    NUMBER_3039: 3039,
    NUMBER_3040: 3040,
    NUMBER_3042: 3042,
    NUMBER_3044: 3044,
    NUMBER_3054: 3054,
    NUMBER_3055: 3055,
    NUMBER_3058: 3058,
    NUMBER_3086: 3086,
    NUMBER_3087: 3087,
    NUMBER_3088: 3088,
    NUMBER_3089: 3089,
    NUMBER_3090: 3090,
    NUMBER_3091: 3091,
    NUMBER_3092: 3092,
    NUMBER_3098: 3098,
    NUMBER_3115: 3115,
    NUMBER_3117: 3117,
    NUMBER_7001: 7001,
    NUMBER_unknown_default_open_api: 11184809
} as const;

export type CustomerBankCodeEnum = typeof CustomerBankCodeEnum[keyof typeof CustomerBankCodeEnum];

