/* tslint:disable */
/* eslint-disable */
/**
 * Cashfree Payment Gateway APIs
 * Cashfree's Payment Gateway APIs provide developers with a streamlined pathway to integrate advanced payment processing capabilities into their applications, platforms and websites.
 *
 * The version of the OpenAPI document: 2026-01-01
 * Contact: developers@cashfree.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Details of the action to be performed. Needed for retry action.
 * @export
 * @interface ManageSubscriptionPaymentRequestActionDetails
 */
export interface ManageSubscriptionPaymentRequestActionDetails {
    /**
     * Next scheduled time for the retry of the FAILED payment. Required for retry action.    Please note that only the date component is considered. Any time value provided will be ignored.
     * @type {string}
     * @memberof ManageSubscriptionPaymentRequestActionDetails
     */
    'next_scheduled_time'?: string;
}
