/* tslint:disable */
/* eslint-disable */
/**
 * Cashfree Payment Gateway APIs
 * Cashfree's Payment Gateway APIs provide developers with a streamlined pathway to integrate advanced payment processing capabilities into their applications, platforms and websites.
 *
 * The version of the OpenAPI document: 2026-01-01
 * Contact: developers@cashfree.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Allowed payment modes for this order. credit_card, debit_card, netbanking, paylater, etc are the values that can be passed to this parameter.
 * @export
 * @interface OrderMetaPaymentMethodsFiltersMethods
 */
export interface OrderMetaPaymentMethodsFiltersMethods {
    /**
     * It accepts value of \"ALLOW\" and allows only those modes present in it's neighbouring parameter \"values.\".
     * @type {string}
     * @memberof OrderMetaPaymentMethodsFiltersMethods
     */
    'action'?: string;
    /**
     * The accepted entries for this paramter are \"debit_card, credit_card, prepaid_card, upi, wallet, netbanking, banktransfer, paylater, paypal, debit_card_emi, credit_card_emi, upi_credit_card, upi_ppi, cardless_emi, account_based_payment, corporate_credit_card, sbc_debit_card, sbc_emandate, sbc_upi, sbc_credit_card.\".
     * @type {List<string>}
     * @memberof OrderMetaPaymentMethodsFiltersMethods
     */
    'values'?: List<string>;
}
