/*
 * Cashfree Payment Gateway APIs
 *
 * Cashfree's Payment Gateway APIs provide developers with a streamlined pathway to integrate advanced payment processing capabilities into their applications, platforms and websites.
 *
 * The version of the OpenAPI document: 2026-01-01
 * Contact: developers@cashfree.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = cashfree-dotnet-pg-sdk.Client.OpenAPIDateConverter;

namespace cashfree-dotnet-pg-sdk.Model
{
    /// <summary>
    /// OrderExtendedDataEntity
    /// </summary>
    [DataContract(Name = "OrderExtendedDataEntity")]
    public class OrderExtendedDataEntity : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="OrderExtendedDataEntity" /> class.
        /// </summary>
        /// <param name="">unique id generated by cashfree for your order..</param>
        /// <param name="">order_id sent during the api request..</param>
        /// <param name="">.</param>
        /// <param name="">Currency of the order. Example INR..</param>
        /// <param name="">When the order was created at cashfree&#39;s server..</param>
        /// <param name="">.</param>
        /// <param name="">.</param>
        /// <param name="">.</param>
        /// <param name="">.</param>
        /// <param name="">.</param>
        /// <param name="">.</param>
        public OrderExtendedDataEntity(string?  = default(string?), string?  = default(string?), decimal?  = default(decimal?), string?  = default(string?), string?  = default(string?), ChargesEntity?  = default(ChargesEntity?), ExtendedCustomerDetails?  = default(ExtendedCustomerDetails?), AddressDetails?  = default(AddressDetails?), AddressDetails?  = default(AddressDetails?), ExtendedCartDetails?  = default(ExtendedCartDetails?), List<OfferExtendedDetails>?  = default(List<OfferExtendedDetails>?))
        {
            this.cf_order_id = ;
            this.order_id = ;
            this.order_amount = ;
            this.order_currency = ;
            this.created_at = ;
            this.charges = ;
            this.customer_details = ;
            this.shipping_address = ;
            this.billing_address = ;
            this.cart = ;
            this.offers = ;
        }

        /// <summary>
        /// unique id generated by cashfree for your order.
        /// </summary>
        /// <value>unique id generated by cashfree for your order.</value>
        [DataMember(Name = "cf_order_id", EmitDefaultValue = false)]
        public string? cf_order_id { get; set; }

        /// <summary>
        /// order_id sent during the api request.
        /// </summary>
        /// <value>order_id sent during the api request.</value>
        [DataMember(Name = "order_id", EmitDefaultValue = false)]
        public string? order_id { get; set; }

        /// <summary>
        /// Gets or Sets order_amount
        /// </summary>
        [DataMember(Name = "order_amount", EmitDefaultValue = false)]
        public decimal? order_amount { get; set; }

        /// <summary>
        /// Currency of the order. Example INR.
        /// </summary>
        /// <value>Currency of the order. Example INR.</value>
        [DataMember(Name = "order_currency", EmitDefaultValue = false)]
        public string? order_currency { get; set; }

        /// <summary>
        /// When the order was created at cashfree&#39;s server.
        /// </summary>
        /// <value>When the order was created at cashfree&#39;s server.</value>
        /// <example>2022-08-16T14:45:38+05:30</example>
        [DataMember(Name = "created_at", EmitDefaultValue = false)]
        public string? created_at { get; set; }

        /// <summary>
        /// Gets or Sets charges
        /// </summary>
        [DataMember(Name = "charges", EmitDefaultValue = false)]
        public ChargesEntity? charges { get; set; }

        /// <summary>
        /// Gets or Sets customer_details
        /// </summary>
        [DataMember(Name = "customer_details", EmitDefaultValue = false)]
        public ExtendedCustomerDetails? customer_details { get; set; }

        /// <summary>
        /// Gets or Sets shipping_address
        /// </summary>
        [DataMember(Name = "shipping_address", EmitDefaultValue = false)]
        public AddressDetails? shipping_address { get; set; }

        /// <summary>
        /// Gets or Sets billing_address
        /// </summary>
        [DataMember(Name = "billing_address", EmitDefaultValue = false)]
        public AddressDetails? billing_address { get; set; }

        /// <summary>
        /// Gets or Sets cart
        /// </summary>
        [DataMember(Name = "cart", EmitDefaultValue = false)]
        public ExtendedCartDetails? cart { get; set; }

        /// <summary>
        /// Gets or Sets offers
        /// </summary>
        [DataMember(Name = "offers", EmitDefaultValue = false)]
        public List<OfferExtendedDetails>? offers { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class OrderExtendedDataEntity {\n");
            sb.Append("  cf_order_id: ").Append(cf_order_id).Append("\n");
            sb.Append("  order_id: ").Append(order_id).Append("\n");
            sb.Append("  order_amount: ").Append(order_amount).Append("\n");
            sb.Append("  order_currency: ").Append(order_currency).Append("\n");
            sb.Append("  created_at: ").Append(created_at).Append("\n");
            sb.Append("  charges: ").Append(charges).Append("\n");
            sb.Append("  customer_details: ").Append(customer_details).Append("\n");
            sb.Append("  shipping_address: ").Append(shipping_address).Append("\n");
            sb.Append("  billing_address: ").Append(billing_address).Append("\n");
            sb.Append("  cart: ").Append(cart).Append("\n");
            sb.Append("  offers: ").Append(offers).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }    }

}
