/* tslint:disable */
/* eslint-disable */
/**
 * Cashfree Payment Gateway APIs
 * Cashfree's Payment Gateway APIs provide developers with a streamlined pathway to integrate advanced payment processing capabilities into their applications, platforms and websites.
 *
 * The version of the OpenAPI document: 2026-01-01
 * Contact: developers@cashfree.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 * @interface OrderEntity
 */
export interface OrderEntity {
    /**
     * unique id generated by cashfree for your order.
     * @type {string}
     * @memberof OrderEntity
     */
    'cf_order_id'?: string;
    /**
     * order_id sent during the api request.
     * @type {string}
     * @memberof OrderEntity
     */
    'order_id'?: string;
    /**
     * Type of the entity.
     * @type {string}
     * @memberof OrderEntity
     */
    'entity'?: string;
    /**
     * Currency of the order. Example INR.
     * @type {string}
     * @memberof OrderEntity
     */
    'order_currency'?: string;
    /**
     * 
     * @type {decimal}
     * @memberof OrderEntity
     */
    'order_amount'?: decimal;
    /**
     * Possible values are  - `ACTIVE`: Order does not have a sucessful transaction yet - `PAID`: Order is PAID with one successful transaction - `EXPIRED`: Order was not PAID and not it has expired. No transaction can be initiated for an EXPIRED order. `TERMINATED`: Order terminated `TERMINATION_REQUESTED`: Order termination requested.
     * @type {string}
     * @memberof OrderEntity
     */
    'order_status'?: string;
    /**
     * 
     * @type {string}
     * @memberof OrderEntity
     */
    'payment_session_id'?: string;
    /**
     * 
     * @type {string}
     * @memberof OrderEntity
     */
    'order_expiry_time'?: string;
    /**
     * Additional note for order.
     * @type {string}
     * @memberof OrderEntity
     */
    'order_note'?: string;
    /**
     * When the order was created at cashfree's server.
     * @type {string}
     * @memberof OrderEntity
     */
    'created_at'?: string;
    /**
     * 
     * @type {List<VendorSplit>}
     * @memberof OrderEntity
     */
    'order_splits'?: List<VendorSplit>;
    /**
     * 
     * @type {CustomerDetailsResponse}
     * @memberof OrderEntity
     */
    'customer_details'?: CustomerDetailsResponse;
    /**
     * 
     * @type {OrderMeta}
     * @memberof OrderEntity
     */
    'order_meta'?: OrderMeta;
    /**
     * Custom Tags in the form of {\"key\":\"value\"} which can be passed for an order. A maximum of 10 tags can be added.
     * @type {Dictionary<string, string>}
     * @memberof OrderEntity
     */
    'order_tags'?: Dictionary<string, string>;
    /**
     * 
     * @type {CartDetailsEntity}
     * @memberof OrderEntity
     */
    'cart_details'?: CartDetailsEntity;
    /**
     * 
     * @type {TerminalData}
     * @memberof OrderEntity
     */
    'terminal_data'?: TerminalData;
    /**
     * 
     * @type {OrderEntityProducts}
     * @memberof OrderEntity
     */
    'products'?: OrderEntityProducts;
}
