/* tslint:disable */
/* eslint-disable */
/**
 * Cashfree Payment Gateway APIs
 * Cashfree's Payment Gateway APIs provide developers with a streamlined pathway to integrate advanced payment processing capabilities into their applications, platforms and websites.
 *
 * The version of the OpenAPI document: 2026-01-01
 * Contact: developers@cashfree.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 * @interface OrderCreateRefundRequestRefundSplitsInner
 */
export interface OrderCreateRefundRequestRefundSplitsInner {
    /**
     * Vendor id created in Cashfree system.
     * @type {string}
     * @memberof OrderCreateRefundRequestRefundSplitsInner
     */
    'vendor_id': string;
    /**
     * Amount which will be associated with this vendor.
     * @type {decimal}
     * @memberof OrderCreateRefundRequestRefundSplitsInner
     */
    'amount'?: decimal;
    /**
     * Custom Tags in the form of {\"key\":\"value\"} which can be passed for an order. A maximum of 10 tags can be added.
     * @type {Dictionary<string, Object>}
     * @memberof OrderCreateRefundRequestRefundSplitsInner
     */
    'tags'?: Dictionary<string, Object>;
}
