/*
 * Cashfree Payment Gateway APIs
 *
 * Cashfree's Payment Gateway APIs provide developers with a streamlined pathway to integrate advanced payment processing capabilities into their applications, platforms and websites.
 *
 * The version of the OpenAPI document: 2026-01-01
 * Contact: developers@cashfree.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = cashfree-dotnet-pg-sdk.Client.OpenAPIDateConverter;

namespace cashfree-dotnet-pg-sdk.Model
{
    /// <summary>
    /// PARRequest
    /// </summary>
    [DataContract(Name = "PARRequest")]
    public class PARRequest : IValidatableObject
    {
        /// <summary>
        /// Specifies the type of card, with the only accepted value being &#x60;PLAIN_CARD&#x60;.
        /// </summary>
        /// <value>Specifies the type of card, with the only accepted value being &#x60;PLAIN_CARD&#x60;.</value>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum CardTypeEnum
        {
            /// <summary>
            /// Enum PLAINCARD for value: PLAIN_CARD
            /// </summary>
            [EnumMember(Value = "PLAIN_CARD")]
            PLAINCARD = 1
        }

        /// <summary>
        /// Specifies the type of card, with the only accepted value being &#x60;PLAIN_CARD&#x60;.
        /// </summary>
        /// <value>Specifies the type of card, with the only accepted value being &#x60;PLAIN_CARD&#x60;.</value>
        [DataMember(Name = "card_type", EmitDefaultValue = false)]
        public CardTypeEnum? card_type { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="PARRequest" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected PARRequest() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="PARRequest" /> class.
        /// </summary>
        /// <param name="">The card number, containing 15 to 19 numeric digits without spaces or special characters. (required).</param>
        /// <param name="">The Card Verification Value (CVV), a 3-digit code for most cards (Visa, Mastercard) and a 4-digit code for American Express, used for transaction authentication. (required).</param>
        /// <param name="">The two-digit expiry month (01-12), indicating when the card will expire. (required).</param>
        /// <param name="">The two-digit expiry year, representing the last two digits of the card’s expiration year. (required).</param>
        /// <param name="">Specifies the type of card, with the only accepted value being &#x60;PLAIN_CARD&#x60;..</param>
        public PARRequest(string  = default(string), string  = default(string), string  = default(string), string  = default(string), CardTypeEnum?  = default(CardTypeEnum?))
        {
            // to ensure "" is required (not null)
            if ( == null)
            {
                throw new ArgumentNullException(" is a required property for PARRequest and cannot be null");
            }
            this.card_number = ;
            // to ensure "" is required (not null)
            if ( == null)
            {
                throw new ArgumentNullException(" is a required property for PARRequest and cannot be null");
            }
            this.card_cvv = ;
            // to ensure "" is required (not null)
            if ( == null)
            {
                throw new ArgumentNullException(" is a required property for PARRequest and cannot be null");
            }
            this.card_expiry_mm = ;
            // to ensure "" is required (not null)
            if ( == null)
            {
                throw new ArgumentNullException(" is a required property for PARRequest and cannot be null");
            }
            this.card_expiry_yy = ;
            this.card_type = ;
        }

        /// <summary>
        /// The card number, containing 15 to 19 numeric digits without spaces or special characters.
        /// </summary>
        /// <value>The card number, containing 15 to 19 numeric digits without spaces or special characters.</value>
        /// <example>4111111111111111</example>
        [DataMember(Name = "card_number", IsRequired = true, EmitDefaultValue = true)]
        public string card_number { get; set; }

        /// <summary>
        /// The Card Verification Value (CVV), a 3-digit code for most cards (Visa, Mastercard) and a 4-digit code for American Express, used for transaction authentication.
        /// </summary>
        /// <value>The Card Verification Value (CVV), a 3-digit code for most cards (Visa, Mastercard) and a 4-digit code for American Express, used for transaction authentication.</value>
        /// <example>123</example>
        [DataMember(Name = "card_cvv", IsRequired = true, EmitDefaultValue = true)]
        public string card_cvv { get; set; }

        /// <summary>
        /// The two-digit expiry month (01-12), indicating when the card will expire.
        /// </summary>
        /// <value>The two-digit expiry month (01-12), indicating when the card will expire.</value>
        /// <example>12</example>
        [DataMember(Name = "card_expiry_mm", IsRequired = true, EmitDefaultValue = true)]
        public string card_expiry_mm { get; set; }

        /// <summary>
        /// The two-digit expiry year, representing the last two digits of the card’s expiration year.
        /// </summary>
        /// <value>The two-digit expiry year, representing the last two digits of the card’s expiration year.</value>
        /// <example>27</example>
        [DataMember(Name = "card_expiry_yy", IsRequired = true, EmitDefaultValue = true)]
        public string card_expiry_yy { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class PARRequest {\n");
            sb.Append("  card_number: ").Append(card_number).Append("\n");
            sb.Append("  card_cvv: ").Append(card_cvv).Append("\n");
            sb.Append("  card_expiry_mm: ").Append(card_expiry_mm).Append("\n");
            sb.Append("  card_expiry_yy: ").Append(card_expiry_yy).Append("\n");
            sb.Append("  card_type: ").Append(card_type).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }    }

}
