/* tslint:disable */
/* eslint-disable */
/**
 * Cashfree Payment Gateway APIs
 * Cashfree's Payment Gateway APIs provide developers with a streamlined pathway to integrate advanced payment processing capabilities into their applications, platforms and websites.
 *
 * The version of the OpenAPI document: 2026-01-01
 * Contact: developers@cashfree.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 * @interface ReconEntityDataInnerOrderDetails
 */
export interface ReconEntityDataInnerOrderDetails {
    /**
     * Unique order ID. Alphanumeric and only '-' and '_' allowed.
     * @type {string}
     * @memberof ReconEntityDataInnerOrderDetails
     */
    'order_id'?: string;
    /**
     * The amount which was passed at the order creation time.
     * @type {decimal}
     * @memberof ReconEntityDataInnerOrderDetails
     */
    'order_amount'?: decimal;
    /**
     * Order Curreny type - INR.
     * @type {string}
     * @memberof ReconEntityDataInnerOrderDetails
     */
    'order_currency'?: string;
    /**
     * The order tags provided during order creation.
     * @type {Object}
     * @memberof ReconEntityDataInnerOrderDetails
     */
    'order_tags'?: Object;
}
