/* tslint:disable */
/* eslint-disable */
/**
 * Cashfree Payment Gateway APIs
 * Cashfree's Payment Gateway APIs provide developers with a streamlined pathway to integrate advanced payment processing capabilities into their applications, platforms and websites.
 *
 * The version of the OpenAPI document: 2026-01-01
 * Contact: developers@cashfree.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * The refund entity.
 * @export
 * @interface RefundEntity
 */
export interface RefundEntity {
    /**
     * Cashfree Payments ID of the payment for which refund is initiated.
     * @type {string}
     * @memberof RefundEntity
     */
    'cf_payment_id'?: string;
    /**
     * Cashfree Payments ID for a refund.
     * @type {string}
     * @memberof RefundEntity
     */
    'cf_refund_id'?: string;
    /**
     * Merchant’s order Id of the order for which refund is initiated.
     * @type {string}
     * @memberof RefundEntity
     */
    'order_id'?: string;
    /**
     * Merchant’s refund ID of the refund.
     * @type {string}
     * @memberof RefundEntity
     */
    'refund_id'?: string;
    /**
     * Type of object.
     * @type {string}
     * @memberof RefundEntity
     */
    'entity'?: EntityEnum;
    /**
     * Amount that is refunded.
     * @type {decimal}
     * @memberof RefundEntity
     */
    'refund_amount'?: decimal;
    /**
     * Currency of the refund amount.
     * @type {string}
     * @memberof RefundEntity
     */
    'refund_currency'?: string;
    /**
     * Note added by merchant for the refund.
     * @type {string}
     * @memberof RefundEntity
     */
    'refund_note'?: string;
    /**
     * This can be one of [\"SUCCESS\", \"PENDING\", \"CANCELLED\", \"ONHOLD\", \"FAILED\"].
     * @type {string}
     * @memberof RefundEntity
     */
    'refund_status'?: RefundStatusEnum;
    /**
     * The bank reference number for refund.
     * @type {string}
     * @memberof RefundEntity
     */
    'refund_arn'?: string;
    /**
     * Charges in INR for processing refund.
     * @type {decimal}
     * @memberof RefundEntity
     */
    'refund_charge'?: decimal;
    /**
     * Description of refund status.
     * @type {string}
     * @memberof RefundEntity
     */
    'status_description'?: string;
    /**
     * Key-value pair that can be used to store additional information about the entity. Maximum 5 key-value pairs.
     * @type {Object}
     * @memberof RefundEntity
     */
    'metadata'?: Object;
    /**
     * 
     * @type {List<VendorSplit>}
     * @memberof RefundEntity
     */
    'refund_splits'?: List<VendorSplit>;
    /**
     * This can be one of [\"PAYMENT_AUTO_REFUND\", \"MERCHANT_INITIATED\", \"UNRECONCILED_AUTO_REFUND\"].
     * @type {string}
     * @memberof RefundEntity
     */
    'refund_type'?: RefundTypeEnum;
    /**
     * Method or speed of processing refund.
     * @type {string}
     * @memberof RefundEntity
     */
    'refund_mode'?: string;
    /**
     * Time of refund creation.
     * @type {string}
     * @memberof RefundEntity
     */
    'created_at'?: string;
    /**
     * Time when refund was processed successfully.
     * @type {string}
     * @memberof RefundEntity
     */
    'processed_at'?: string;
    /**
     * 
     * @type {RefundSpeed}
     * @memberof RefundEntity
     */
    'refund_speed'?: RefundSpeed;
    /**
     * Cashfree forex conversion charges for refund processing.
     * @type {decimal}
     * @memberof RefundEntity
     */
    'forex_conversion_handling_charge'?: decimal;
    /**
     * Cashfree forex conversion tax for refund processing.
     * @type {decimal}
     * @memberof RefundEntity
     */
    'forex_conversion_handling_tax'?: decimal;
    /**
     * Cashfree forex conversion rate for refund processing.
     * @type {decimal}
     * @memberof RefundEntity
     */
    'forex_conversion_rate'?: decimal;
    /**
     * Cashfree refund charges currency for a refund.
     * @type {string}
     * @memberof RefundEntity
     */
    'charges_currency'?: string;
}

export const EntityEnum = {
    Refund: refund,
    UnknownDefaultOpenApi: unknown_default_open_api
} as const;

export type EntityEnum = typeof EntityEnum[keyof typeof EntityEnum];
export const RefundStatusEnum = {
    SUCCESS: SUCCESS,
    PENDING: PENDING,
    CANCELLED: CANCELLED,
    ONHOLD: ONHOLD,
    UnknownDefaultOpenApi: unknown_default_open_api
} as const;

export type RefundStatusEnum = typeof RefundStatusEnum[keyof typeof RefundStatusEnum];
export const RefundTypeEnum = {
    PAYMENTAUTOREFUND: PAYMENT_AUTO_REFUND,
    MERCHANTINITIATED: MERCHANT_INITIATED,
    UNRECONCILEDAUTOREFUND: UNRECONCILED_AUTO_REFUND,
    UnknownDefaultOpenApi: unknown_default_open_api
} as const;

export type RefundTypeEnum = typeof RefundTypeEnum[keyof typeof RefundTypeEnum];

