/*
 * Cashfree Payment Gateway APIs
 *
 * Cashfree's Payment Gateway APIs provide developers with a streamlined pathway to integrate advanced payment processing capabilities into their applications, platforms and websites.
 *
 * The version of the OpenAPI document: 2026-01-01
 * Contact: developers@cashfree.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = cashfree-dotnet-pg-sdk.Client.OpenAPIDateConverter;

namespace cashfree-dotnet-pg-sdk.Model
{
    /// <summary>
    /// Subscription customer details.
    /// </summary>
    [DataContract(Name = "SubscriptionCustomerDetails")]
    public class SubscriptionCustomerDetails : IValidatableObject
    {
        /// <summary>
        /// Bank account type of the customer.
        /// </summary>
        /// <value>Bank account type of the customer.</value>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum CustomerBankAccountTypeEnum
        {
            /// <summary>
            /// Enum SAVINGS for value: SAVINGS
            /// </summary>
            [EnumMember(Value = "SAVINGS")]
            SAVINGS = 1,

            /// <summary>
            /// Enum CURRENT for value: CURRENT
            /// </summary>
            [EnumMember(Value = "CURRENT")]
            CURRENT = 2
        }

        /// <summary>
        /// Bank account type of the customer.
        /// </summary>
        /// <value>Bank account type of the customer.</value>
        [DataMember(Name = "customer_bank_account_type", EmitDefaultValue = false)]
        public CustomerBankAccountTypeEnum? customer_bank_account_type { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="SubscriptionCustomerDetails" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected SubscriptionCustomerDetails() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="SubscriptionCustomerDetails" /> class.
        /// </summary>
        /// <param name="">Name of the customer..</param>
        /// <param name="">Email of the customer. (required).</param>
        /// <param name="">Phone number of the customer. (required).</param>
        /// <param name="">Bank holder name of the customer. Account holder name is mandatory for TPV transaction. Max character allowed is 40..</param>
        /// <param name="">Bank account number of the customer. Conditional Parameter. Max character allowed is 35..</param>
        /// <param name="">IFSC code of the customer. For a TPV transaction, send at least one out of &#x60;customer_bank_code&#x60; or &#x60;customer_bank_ifsc&#x60;..</param>
        /// <param name="">Bank code of the customer. Refer to the list of Live Banks in API E-Mandate [here](https://www.npci.org.in/product/nach/all-members). For a TPV transactions, include at least one of &#x60;customer_bank_code&#x60; or &#x60;customer_bank_ifsc&#x60;..</param>
        /// <param name="">Bank account type of the customer..</param>
        public SubscriptionCustomerDetails(string?  = default(string?), string  = default(string), string  = default(string), string?  = default(string?), string?  = default(string?), string?  = default(string?), string?  = default(string?), CustomerBankAccountTypeEnum?  = default(CustomerBankAccountTypeEnum?))
        {
            // to ensure "" is required (not null)
            if ( == null)
            {
                throw new ArgumentNullException(" is a required property for SubscriptionCustomerDetails and cannot be null");
            }
            this.customer_email = ;
            // to ensure "" is required (not null)
            if ( == null)
            {
                throw new ArgumentNullException(" is a required property for SubscriptionCustomerDetails and cannot be null");
            }
            this.customer_phone = ;
            this.customer_name = ;
            this.customer_bank_account_holder_name = ;
            this.customer_bank_account_number = ;
            this.customer_bank_ifsc = ;
            this.customer_bank_code = ;
            this.customer_bank_account_type = ;
        }

        /// <summary>
        /// Name of the customer.
        /// </summary>
        /// <value>Name of the customer.</value>
        [DataMember(Name = "customer_name", EmitDefaultValue = false)]
        public string? customer_name { get; set; }

        /// <summary>
        /// Email of the customer.
        /// </summary>
        /// <value>Email of the customer.</value>
        [DataMember(Name = "customer_email", IsRequired = true, EmitDefaultValue = true)]
        public string customer_email { get; set; }

        /// <summary>
        /// Phone number of the customer.
        /// </summary>
        /// <value>Phone number of the customer.</value>
        [DataMember(Name = "customer_phone", IsRequired = true, EmitDefaultValue = true)]
        public string customer_phone { get; set; }

        /// <summary>
        /// Bank holder name of the customer. Account holder name is mandatory for TPV transaction. Max character allowed is 40.
        /// </summary>
        /// <value>Bank holder name of the customer. Account holder name is mandatory for TPV transaction. Max character allowed is 40.</value>
        [DataMember(Name = "customer_bank_account_holder_name", EmitDefaultValue = false)]
        public string? customer_bank_account_holder_name { get; set; }

        /// <summary>
        /// Bank account number of the customer. Conditional Parameter. Max character allowed is 35.
        /// </summary>
        /// <value>Bank account number of the customer. Conditional Parameter. Max character allowed is 35.</value>
        [DataMember(Name = "customer_bank_account_number", EmitDefaultValue = false)]
        public string? customer_bank_account_number { get; set; }

        /// <summary>
        /// IFSC code of the customer. For a TPV transaction, send at least one out of &#x60;customer_bank_code&#x60; or &#x60;customer_bank_ifsc&#x60;.
        /// </summary>
        /// <value>IFSC code of the customer. For a TPV transaction, send at least one out of &#x60;customer_bank_code&#x60; or &#x60;customer_bank_ifsc&#x60;.</value>
        [DataMember(Name = "customer_bank_ifsc", EmitDefaultValue = false)]
        public string? customer_bank_ifsc { get; set; }

        /// <summary>
        /// Bank code of the customer. Refer to the list of Live Banks in API E-Mandate [here](https://www.npci.org.in/product/nach/all-members). For a TPV transactions, include at least one of &#x60;customer_bank_code&#x60; or &#x60;customer_bank_ifsc&#x60;.
        /// </summary>
        /// <value>Bank code of the customer. Refer to the list of Live Banks in API E-Mandate [here](https://www.npci.org.in/product/nach/all-members). For a TPV transactions, include at least one of &#x60;customer_bank_code&#x60; or &#x60;customer_bank_ifsc&#x60;.</value>
        [DataMember(Name = "customer_bank_code", EmitDefaultValue = false)]
        public string? customer_bank_code { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class SubscriptionCustomerDetails {\n");
            sb.Append("  customer_name: ").Append(customer_name).Append("\n");
            sb.Append("  customer_email: ").Append(customer_email).Append("\n");
            sb.Append("  customer_phone: ").Append(customer_phone).Append("\n");
            sb.Append("  customer_bank_account_holder_name: ").Append(customer_bank_account_holder_name).Append("\n");
            sb.Append("  customer_bank_account_number: ").Append(customer_bank_account_number).Append("\n");
            sb.Append("  customer_bank_ifsc: ").Append(customer_bank_ifsc).Append("\n");
            sb.Append("  customer_bank_code: ").Append(customer_bank_code).Append("\n");
            sb.Append("  customer_bank_account_type: ").Append(customer_bank_account_type).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }    }

}
