/* tslint:disable */
/* eslint-disable */
/**
 * Cashfree Payment Gateway APIs
 * Cashfree's Payment Gateway APIs provide developers with a streamlined pathway to integrate advanced payment processing capabilities into their applications, platforms and websites.
 *
 * The version of the OpenAPI document: 2026-01-01
 * Contact: developers@cashfree.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 * @interface UPIDowntimeUpi
 */
export interface UPIDowntimeUpi {
    /**
     * 
     * @type {List<string>}
     * @memberof UPIDowntimeUpi
     */
    'upi_issuer'?: List<string>;
    /**
     * 
     * @type {List<string>}
     * @memberof UPIDowntimeUpi
     */
    'upi_psp'?: List<string>;
    /**
     * 
     * @type {List<string>}
     * @memberof UPIDowntimeUpi
     */
    'upi_vpa'?: List<string>;
    /**
     * 
     * @type {bool}
     * @memberof UPIDowntimeUpi
     */
    'is_npci_downtime'?: bool;
}
