/* tslint:disable */
/* eslint-disable */
/**
 * Cashfree Payment Gateway APIs
 * Cashfree's Payment Gateway APIs provide developers with a streamlined pathway to integrate advanced payment processing capabilities into their applications, platforms and websites.
 *
 * The version of the OpenAPI document: 2026-01-01
 * Contact: developers@cashfree.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Vendor Recon Request body.
 * @export
 * @interface VendorReconRequest
 */
export interface VendorReconRequest {
    /**
     * 
     * @type {VendorReconRequestPagination}
     * @memberof VendorReconRequest
     */
    'pagination': VendorReconRequestPagination;
    /**
     * 
     * @type {VendorReconRequestFilters}
     * @memberof VendorReconRequest
     */
    'filters': VendorReconRequestFilters;
}
