/*
 * Cashfree Payment Gateway APIs
 *
 * Cashfree's Payment Gateway APIs provide developers with a streamlined pathway to integrate advanced payment processing capabilities into their applications, platforms and websites.
 *
 * The version of the OpenAPI document: 2026-01-01
 * Contact: developers@cashfree.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using cashfree-dotnet-pg-sdk.Client;
using cashfree-dotnet-pg-sdk.Api;
// uncomment below to import models
//using cashfree-dotnet-pg-sdk.Model;

namespace cashfree-dotnet-pg-sdk.Test.Api
{
    /// <summary>
    ///  Class for testing PGReconciliationApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class PGReconciliationApiTests : IDisposable
    {
        public PGReconciliationApiTests()
        {
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PGReconciliationApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' PGReconciliationApi
            //Assert.IsType<PGReconciliationApi>(instance);
        }

        /// <summary>
        /// Test PGFetchRecon
        /// </summary>
        [Fact]
        public void PGFetchReconTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string xApiVersion = null;
            //FetchReconRequest fetchReconRequest = null;
            //string? contentType = null;
            //string? xRequestId = null;
            //Guid? xIdempotencyKey = null;
            //string? accept = null;
            //var response = instance.PGFetchRecon(xApiVersion, fetchReconRequest, contentType, xRequestId, xIdempotencyKey, accept);
            //Assert.IsType<ReconEntity>(response);
        }
    }
}
